var h;h||(h=typeof Module !== 'undefined' ? Module : {});h.Be||(h.Be=0);h.Be++;
h.ENVIRONMENT_IS_PTHREAD||h.$ww||function(a){function b(n,p,t){var q=new XMLHttpRequest;q.open("GET",n,!0);q.responseType="arraybuffer";q.onprogress=function(u){var x=p;u.total&&(x=u.total);if(u.loaded){q.Nd?h.ee[n].loaded=u.loaded:(q.Nd=!0,h.ee||(h.ee={}),h.ee[n]={loaded:u.loaded,total:x});var P=x=u=0,X;for(X in h.ee){var Y=h.ee[X];u+=Y.total;x+=Y.loaded;P++}u=Math.ceil(u*h.Be/P);h.setStatus&&h.setStatus(`Downloading data... (${x}/${u})`)}else!h.ee&&h.setStatus&&h.setStatus("Downloading data...")};
q.onerror=function(){throw Error("NetworkError for: "+n);};q.onload=function(){if(200==q.status||304==q.status||206==q.status||0==q.status&&q.response)t(q.response);else throw Error(q.statusText+" : "+q.responseURL);};q.send(null)}function c(n){console.error("package error:",n)}function d(){function n(u,x,P){this.start=u;this.end=x;this.audio=P}function p(u){if(!u)throw"Loading data file failed."+Error().stack;if(u.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;
u=new Uint8Array(u);n.prototype.ye=u;u=a.files;for(var x=0;x<u.length;++x)n.prototype.Nd[u[x].filename].onload();h.removeRunDependency("datafile_tetrism.data")}h.FS_createPath("/","font",!0,!0);n.prototype={Nd:{},open:function(u,x){this.name=x;this.Nd[x]=this;h.addRunDependency(`fp ${this.name}`)},onload:function(){this.finish(this.ye.subarray(this.start,this.end))},finish:function(u){h.FS_createDataFile(this.name,null,u,!0,!0,!0);h.removeRunDependency(`fp ${this.name}`);this.Nd[this.name]=null}};
for(var t=a.files,q=0;q<t.length;++q)(new n(t[q].start,t[q].end,t[q].audio||0)).open("GET",t[q].filename);h.addRunDependency("datafile_tetrism.data");h.Ze||(h.Ze={});h.Ze["tetrism.data"]={Vf:!1};m?(p(m),m=null):g=p}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+
"/");"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=h.locateFile?h.locateFile("tetrism.data",""):"tetrism.data",f=a.remote_package_size,g=null,m=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;m||b(e,f,function(n){g?(g(n),g=null):m=n},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))}({files:[{filename:"/font/AldotheApache.ttf",
start:0,end:17092}],remote_package_size:17092});var aa=Object.assign({},h),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="",fa,ha,ia;"undefined"!=typeof document&&document.currentScript&&(ea=document.currentScript.src);ea=0!==ea.indexOf("blob:")?ea.substr(0,ea.replace(/[?#].*/,"").lastIndexOf("/")+1):"";fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText};
ha=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};ia=a=>{document.title=a};var ja=h.print||console.log.bind(console),k=h.printErr||console.error.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);h.quit&&(da=h.quit);var ka;h.wasmBinary&&(ka=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;
"object"!=typeof WebAssembly&&l("no native wasm support detected");var la,r,ma=!1,na,v,w,oa,pa,y,z,A,qa,B,C,ra=[],sa=[],ta=[],ua=[],va=[];function wa(){var a=h.preRun.shift();ra.unshift(a)}var xa=0,ya=null,za=null;function Aa(){xa++;h.monitorRunDependencies&&h.monitorRunDependencies(xa)}function Ba(){xa--;h.monitorRunDependencies&&h.monitorRunDependencies(xa);if(0==xa&&(null!==ya&&(clearInterval(ya),ya=null),za)){var a=za;za=null;a()}}
function l(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";k(a);ma=!0;na=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Ca(a){return a.startsWith("data:application/octet-stream;base64,")}var Da;Da="tetrism.wasm";if(!Ca(Da)){var Ea=Da;Da=h.locateFile?h.locateFile(Ea,ea):ea+Ea}function Fa(a){if(a==Da&&ka)return new Uint8Array(ka);throw"both async and sync fetching of the wasm failed";}
function Ga(a){return ka||"function"!=typeof fetch?Promise.resolve().then(()=>Fa(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Fa(a))}function Ha(a,b,c){return Ga(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{k("failed to asynchronously prepare wasm: "+d);l(d)})}
function Ia(a,b){var c=Da;ka||"function"!=typeof WebAssembly.instantiateStreaming||Ca(c)||"function"!=typeof fetch?Ha(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){k("wasm streaming compile failed: "+e);k("falling back to ArrayBuffer instantiation");return Ha(c,a,b)}))}
var La={281296:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,281443:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,281677:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.Md||("undefined"!==typeof AudioContext?b.Md=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.Md=new webkitAudioContext),b.Md&&
Ja(b.Md));return void 0===b.Md?-1:0},282170:()=>h.SDL2.Md.sampleRate,282238:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.capture.le&&(clearTimeout(g.capture.le),g.capture.le=void 0);g.capture.se=g.Md.createMediaStreamSource(m);g.capture.Qd=g.Md.createScriptProcessor(b,a,1);g.capture.Qd.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.Ae=n.inputBuffer,n=[d],C.get(c).apply(null,n))};g.capture.se.connect(g.capture.Qd);g.capture.Qd.connect(g.Md.destination);
g.capture.stream=m}var g=h.SDL2;g.capture.ve=g.Md.createBuffer(a,b,g.Md.sampleRate);g.capture.ve.getChannelData(0).fill(0);g.capture.le=setTimeout(function(){g.capture.Ae=g.capture.ve;var m=[d];C.get(c).apply(null,m)},b/g.Md.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},283890:(a,b,c,
d)=>{var e=h.SDL2;e.audio.Qd=e.Md.createScriptProcessor(b,0,a);e.audio.Qd.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Oe=f.outputBuffer,f=[d],C.get(c).apply(null,f))};e.audio.Qd.connect(e.Md.destination)},284300:(a,b)=>{for(var c=h.SDL2,d=c.capture.Ae.numberOfChannels,e=0;e<d;++e){var f=c.capture.Ae.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Ka(a+
4*g,f[g]);else for(g=0;g<b;++g)Ka(a+4*(g*d+e),f[g])}},284905:(a,b)=>{for(var c=h.SDL2,d=c.audio.Oe.numberOfChannels,e=0;e<d;++e){var f=c.audio.Oe.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=A[a+(g*d+e<<2)>>2]}},285385:a=>{var b=h.SDL2;if(a){void 0!==b.capture.le&&clearTimeout(b.capture.le);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.Qd&&(b.capture.Qd.onaudioprocess=function(){},b.capture.Qd.disconnect(),b.capture.Qd=void 0);void 0!==b.capture.se&&(b.capture.se.disconnect(),b.capture.se=void 0);void 0!==b.capture.ve&&(b.capture.ve=void 0);b.capture=void 0}else void 0!=b.audio.Qd&&(b.audio.Qd.disconnect(),b.audio.Qd=void 0),b.audio=void 0;void 0!==b.Md&&void 0===b.audio&&void 0===b.capture&&(b.Md.close(),b.Md=void 0)},286557:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.hf!==h.canvas&&
(d.Vd=h.createContext(h.canvas,!1,!0),d.hf=h.canvas);if(d.w!==a||d.h!==b||d.tf!==d.Vd)d.image=d.Vd.createImageData(a,b),d.w=a,d.h=b,d.tf=d.Vd;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=y[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.lf!==a&&(d.kf=new Int32Array(a.buffer),d.mf=new Uint8Array(a.buffer),d.lf=a),a=d.kf,c=a.length,a.set(y.subarray(b,b+c)),a=d.mf,b=3,e=b+4*c,0==c%8)for(;b<
e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Vd.putImageData(d.image,0,0)},288026:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var p=y[e];b[m]=p&255;b[m+1]=p>>8&255;b[m+2]=p>>16&
255;b[m+3]=p>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(y.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=D(c.length+1);E(c,w,d,c.length+1);return d},289015:a=>{h.canvas&&(h.canvas.style.cursor=a?F(w,a):"")},289098:()=>{h.canvas&&(h.canvas.style.cursor="none")},289167:()=>window.innerWidth,289197:()=>window.innerHeight};
function Ma(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Na=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Ja=a=>{var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Na(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Oa=a=>{for(;0<a.length;)a.shift()(h)};
function Ka(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":v[a>>0]=b;break;case "i8":v[a>>0]=b;break;case "i16":oa[a>>1]=b;break;case "i32":y[a>>2]=b;break;case "i64":qa[a>>3]=BigInt(b);break;case "float":A[a>>2]=b;break;case "double":B[a>>3]=b;break;case "*":z[a>>2]=b;break;default:l(`invalid type for setValue: ${c}`)}}
var Pa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Qa=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Pa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ra=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b},Sa=a=>
{if("/"===a)return"/";a=Qa(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Ta=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);l("initRandomDevice")},Ua=a=>(Ua=Ta())(a);
function Wa(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Pa(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var Xa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,F=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Xa)return Xa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Ya=[],Za=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},E=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&
63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function $a(a){var b=Array(Za(a)+1);a=E(a,b,0,b.length);b.length=a;return b}var ab=[];function bb(a,b){ab[a]={input:[],Pd:[],Zd:b};cb(a,db)}
var db={open:function(a){var b=ab[a.node.ue];if(!b)throw new G(43);a.Kd=b;a.seekable=!1},close:function(a){a.Kd.Zd.oe(a.Kd)},oe:function(a){a.Kd.Zd.oe(a.Kd)},read:function(a,b,c,d){if(!a.Kd||!a.Kd.Zd.Qe)throw new G(60);for(var e=0,f=0;f<d;f++){try{var g=a.Kd.Zd.Qe(a.Kd)}catch(m){throw new G(29);}if(void 0===g&&0===e)throw new G(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Kd||!a.Kd.Zd.Fe)throw new G(60);try{for(var e=0;e<d;e++)a.Kd.Zd.Fe(a.Kd,
b[c+e])}catch(f){throw new G(29);}d&&(a.node.timestamp=Date.now());return e}},eb={Qe:function(){a:{if(!Ya.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}Ya=$a(a)}a=Ya.shift()}return a},Fe:function(a,b){null===b||10===b?(ja(F(a.Pd,0)),a.Pd=[]):0!=b&&a.Pd.push(b)},oe:function(a){a.Pd&&0<a.Pd.length&&(ja(F(a.Pd,0)),a.Pd=[])},wf:function(){return{Nf:25856,
Pf:5,Mf:191,Of:35387,Lf:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},xf:function(){return 0},yf:function(){return[24,80]}},fb={Fe:function(a,b){null===b||10===b?(k(F(a.Pd,0)),a.Pd=[]):0!=b&&a.Pd.push(b)},oe:function(a){a.Pd&&0<a.Pd.length&&(k(F(a.Pd,0)),a.Pd=[])}},hb=a=>{a=65536*Math.ceil(a/65536);var b=gb(65536,a);b?(w.fill(0,b,b+a),a=b):a=0;return a};
function ib(a,b){var c=a.Hd?a.Hd.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Hd,a.Hd=new Uint8Array(b),0<a.Ld&&a.Hd.set(c.subarray(0,a.Ld),0))}
var H={Wd:null,Yd(){return H.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new G(63);H.Wd||(H.Wd={dir:{node:{be:H.Id.be,Rd:H.Id.Rd,ie:H.Id.ie,te:H.Id.te,af:H.Id.af,xe:H.Id.xe,bf:H.Id.bf,$e:H.Id.$e,we:H.Id.we},stream:{de:H.Jd.de}},file:{node:{be:H.Id.be,Rd:H.Id.Rd},stream:{de:H.Jd.de,read:H.Jd.read,write:H.Jd.write,Ke:H.Jd.Ke,Ee:H.Jd.Ee,We:H.Jd.We}},link:{node:{be:H.Id.be,Rd:H.Id.Rd,ke:H.Id.ke},stream:{}},Ne:{node:{be:H.Id.be,Rd:H.Id.Rd},stream:jb}});
c=kb(a,b,c,d);16384===(c.mode&61440)?(c.Id=H.Wd.dir.node,c.Jd=H.Wd.dir.stream,c.Hd={}):32768===(c.mode&61440)?(c.Id=H.Wd.file.node,c.Jd=H.Wd.file.stream,c.Ld=0,c.Hd=null):40960===(c.mode&61440)?(c.Id=H.Wd.link.node,c.Jd=H.Wd.link.stream):8192===(c.mode&61440)&&(c.Id=H.Wd.Ne.node,c.Jd=H.Wd.Ne.stream);c.timestamp=Date.now();a&&(a.Hd[b]=c,a.timestamp=c.timestamp);return c},Xf(a){return a.Hd?a.Hd.subarray?a.Hd.subarray(0,a.Ld):new Uint8Array(a.Hd):new Uint8Array(0)},Id:{be(a){var b={};b.Tf=8192===(a.mode&
61440)?a.id:1;b.Zf=a.id;b.mode=a.mode;b.dg=1;b.uid=0;b.Yf=0;b.ue=a.ue;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ld:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Jf=new Date(a.timestamp);b.bg=new Date(a.timestamp);b.Sf=new Date(a.timestamp);b.gf=4096;b.Kf=Math.ceil(b.size/b.gf);return b},Rd(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.Ld!=b))if(0==b)a.Hd=null,a.Ld=0;else{var c=a.Hd;a.Hd=new Uint8Array(b);
c&&a.Hd.set(c.subarray(0,Math.min(b,a.Ld)));a.Ld=b}},ie(){throw lb[44];},te(a,b,c,d){return H.createNode(a,b,c,d)},af(a,b,c){if(16384===(a.mode&61440)){try{var d=mb(b,c)}catch(f){}if(d)for(var e in d.Hd)throw new G(55);}delete a.parent.Hd[a.name];a.parent.timestamp=Date.now();a.name=c;b.Hd[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},xe(a,b){delete a.Hd[b];a.timestamp=Date.now()},bf(a,b){var c=mb(a,b),d;for(d in c.Hd)throw new G(55);delete a.Hd[b];a.timestamp=Date.now()},$e(a){var b=[".",".."],
c;for(c in a.Hd)a.Hd.hasOwnProperty(c)&&b.push(c);return b},we(a,b,c){a=H.createNode(a,b,41471,0);a.link=c;return a},ke(a){if(40960!==(a.mode&61440))throw new G(28);return a.link}},Jd:{read(a,b,c,d,e){var f=a.node.Hd;if(e>=a.node.Ld)return 0;a=Math.min(a.node.Ld-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Hd||a.Hd.subarray)){if(f)return a.Hd=b.subarray(c,c+d),a.Ld=
d;if(0===a.Ld&&0===e)return a.Hd=b.slice(c,c+d),a.Ld=d;if(e+d<=a.Ld)return a.Hd.set(b.subarray(c,c+d),e),d}ib(a,e+d);if(a.Hd.subarray&&b.subarray)a.Hd.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Hd[e+f]=b[c+f];a.Ld=Math.max(a.Ld,e+d);return d},de(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ld);if(0>b)throw new G(28);return b},Ke(a,b,c){ib(a.node,b+c);a.node.Ld=Math.max(a.node.Ld,b+c)},Ee(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new G(43);a=a.node.Hd;if(e&2||
a.buffer!==v.buffer){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;b=hb(b);if(!b)throw new G(48);v.set(a,b)}else c=!1,b=a.byteOffset;return{Bf:b,ff:c}},We(a,b,c,d){H.Jd.write(a,b,0,d,c,!1);return 0}}},nb=(a,b,c)=>{var d=`al ${a}`;ha(a,e=>{e||l(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(e));d&&Ba(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Aa(d)},ob=h.preloadPlugins||[];
function pb(a,b,c,d){"undefined"!=typeof qb&&rb();var e=!1;ob.forEach(function(f){!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e}function sb(a,b,c,d,e,f,g,m,n,p){function t(x){function P(X){p&&p();m||tb(a,b,X,d,e,n);f&&f();Ba(u)}pb(x,q,P,()=>{g&&g();Ba(u)})||P(x)}var q=b?Wa(Qa(a+"/"+b)):a,u=`cp ${q}`;Aa(u);"string"==typeof c?nb(c,x=>t(x),g):t(c)}function ub(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
var wb=null,xb={},yb=[],zb=1,Ab=null,Bb=!0,G=null,lb={},Db=(a,b={})=>{a=Wa(a);if(!a)return{path:"",node:null};b=Object.assign({Pe:!0,Ge:0},b);if(8<b.Ge)throw new G(32);a=a.split("/").filter(g=>!!g);for(var c=wb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=mb(c,a[e]);d=Qa(d+"/"+a[e]);c.je&&(!f||f&&b.Pe)&&(c=c.je.root);if(!f||b.Ce)for(f=0;40960===(c.mode&61440);)if(c=Cb(d),d=Wa(Ra(d),c),c=Db(d,{Ge:b.Ge+1}).node,40<f++)throw new G(32);}return{path:d,node:c}},Eb=a=>{for(var b;;){if(a===
a.parent)return a=a.Yd.Ve,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},Fb=(a,b)=>{for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Ab.length},mb=(a,b)=>{var c;if(c=(c=Gb(a,"x"))?c:a.Id.ie?0:2)throw new G(c,a);for(c=Ab[Fb(a.id,b)];c;c=c.fe){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Id.ie(a,b)},kb=(a,b,c,d)=>{a=new Hb(a,b,c,d);b=Fb(a.parent.id,a.name);a.fe=Ab[b];return Ab[b]=a},Ib=a=>{var b=["r","w","rw"][a&3];a&512&&(b+=
"w");return b},Gb=(a,b)=>{if(Bb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0},Jb=(a,b)=>{try{return mb(a,b),20}catch(c){}return Gb(a,"wx")},Kb=()=>{for(var a=0;4096>=a;a++)if(!yb[a])return a;throw new G(33);},Lb=a=>{a=yb[a];if(!a)throw new G(8);return a},Nb=(a,b=-1)=>{Mb||(Mb=function(){this.Nd={}},Mb.prototype={},Object.defineProperties(Mb.prototype,{object:{get(){return this.node},set(c){this.node=c}},
flags:{get(){return this.Nd.flags},set(c){this.Nd.flags=c}},position:{get(){return this.Nd.position},set(c){this.Nd.position=c}}}));a=Object.assign(new Mb,a);-1==b&&(b=Kb());a.fd=b;return yb[b]=a},jb={open:a=>{a.Jd=xb[a.node.ue].Jd;a.Jd.open&&a.Jd.open(a)},de:()=>{throw new G(70);}},cb=(a,b)=>{xb[a]={Jd:b}},Ob=(a,b)=>{var c="/"===b,d=!b;if(c&&wb)throw new G(10);if(!c&&!d){var e=Db(b,{Pe:!1});b=e.path;e=e.node;if(e.je)throw new G(10);if(16384!==(e.mode&61440))throw new G(54);}b={type:a,gg:{},Ve:b,
Af:[]};a=a.Yd(b);a.Yd=b;b.root=a;c?wb=a:e&&(e.je=b,e.Yd&&e.Yd.Af.push(b))},I=(a,b,c)=>{var d=Db(a,{parent:!0}).node;a=Sa(a);if(!a||"."===a||".."===a)throw new G(28);var e=Jb(d,a);if(e)throw new G(e);if(!d.Id.te)throw new G(63);return d.Id.te(d,a,b,c)},Pb=(a,b,c)=>{"undefined"==typeof c&&(c=b,b=438);return I(a,b|8192,c)},Qb=(a,b)=>{if(!Wa(a))throw new G(44);var c=Db(b,{parent:!0}).node;if(!c)throw new G(44);b=Sa(b);var d=Jb(c,b);if(d)throw new G(d);if(!c.Id.we)throw new G(63);c.Id.we(c,b,a)},Rb=a=>
{var b=Db(a,{parent:!0}).node;if(!b)throw new G(44);var c=Sa(a);a=mb(b,c);a:{try{var d=mb(b,c)}catch(f){d=f.ae;break a}var e=Gb(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new G(d);if(!b.Id.xe)throw new G(63);if(a.je)throw new G(10);b.Id.xe(b,c);b=Fb(a.parent.id,a.name);if(Ab[b]===a)Ab[b]=a.fe;else for(b=Ab[b];b;){if(b.fe===a){b.fe=a.fe;break}b=b.fe}},Cb=a=>{a=Db(a).node;if(!a)throw new G(44);if(!a.Id.ke)throw new G(28);return Wa(Eb(a.parent),a.Id.ke(a))},Sb=(a,b)=>{a="string"==typeof a?
Db(a,{Ce:!0}).node:a;if(!a.Id.Rd)throw new G(63);a.Id.Rd(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})},Ub=(a,b,c)=>{if(""===a)throw new G(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Qa(a);try{e=Db(a,{Ce:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new G(20);}else e=I(a,c,0),d=!0;
if(!e)throw new G(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new G(54);if(!d&&(c=e?40960===(e.mode&61440)?32:16384===(e.mode&61440)&&("r"!==Ib(b)||b&512)?31:Gb(e,Ib(b)):44))throw new G(c);if(b&512&&!d){c=e;c="string"==typeof c?Db(c,{Ce:!0}).node:c;if(!c.Id.Rd)throw new G(63);if(16384===(c.mode&61440))throw new G(31);if(32768!==(c.mode&61440))throw new G(28);if(d=Gb(c,"w"))throw new G(d);c.Id.Rd(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Nb({node:e,path:Eb(e),
flags:b,seekable:!0,position:0,Jd:e.Jd,Ff:[],error:!1});e.Jd.open&&e.Jd.open(e);!h.logReadFiles||b&1||(Tb||(Tb={}),a in Tb||(Tb[a]=1));return e},Vb=a=>{if(null===a.fd)throw new G(8);a.De&&(a.De=null);try{a.Jd.close&&a.Jd.close(a)}catch(b){throw b;}finally{yb[a.fd]=null}a.fd=null},Wb=(a,b,c)=>{if(null===a.fd)throw new G(8);if(!a.seekable||!a.Jd.de)throw new G(70);if(0!=c&&1!=c&&2!=c)throw new G(28);a.position=a.Jd.de(a,b,c);a.Ff=[]},Xb=(a,b,c,d,e,f)=>{if(0>d||0>e)throw new G(28);if(null===a.fd)throw new G(8);
if(0===(a.flags&2097155))throw new G(8);if(16384===(a.node.mode&61440))throw new G(31);if(!a.Jd.write)throw new G(28);a.seekable&&a.flags&1024&&Wb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new G(70);b=a.Jd.write(a,b,c,d,e,f);g||(a.position+=b);return b},Yb=()=>{G||(G=function(a,b){this.name="ErrnoError";this.node=b;this.Df=function(c){this.ae=c};this.Df(a);this.message="FS error"},G.prototype=Error(),G.prototype.constructor=G,[44].forEach(a=>{lb[a]=new G(a);lb[a].stack=
"<generic error, no stack>"}))},Zb,$b=(a,b)=>{a="string"==typeof a?a:Eb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Qa(a+"/"+c);try{I(d,16895,0)}catch(e){}a=d}}return d},ac=(a,b,c,d)=>{a=Qa(("string"==typeof a?a:Eb(a))+"/"+b);c=ub(c,d);return I(a,(void 0!==c?c:438)&4095|32768,0)},tb=(a,b,c,d,e,f)=>{var g=b;a&&(a="string"==typeof a?a:Eb(a),g=b?Qa(a+"/"+b):a);a=ub(d,e);g=I(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<
e;++d)b[d]=c.charCodeAt(d);c=b}Sb(g,a|146);b=Ub(g,577);Xb(b,c,0,c.length,0,f);Vb(b);Sb(g,a)}return g},J=(a,b,c,d)=>{a=Qa(("string"==typeof a?a:Eb(a))+"/"+b);b=ub(!!c,!!d);J.Te||(J.Te=64);var e=J.Te++<<8|0;cb(e,{open:f=>{f.seekable=!1},close:()=>{d&&d.buffer&&d.buffer.length&&d(10)},read:(f,g,m,n)=>{for(var p=0,t=0;t<n;t++){try{var q=c()}catch(u){throw new G(29);}if(void 0===q&&0===p)throw new G(6);if(null===q||void 0===q)break;p++;g[m+t]=q}p&&(f.node.timestamp=Date.now());return p},write:(f,g,m,n)=>
{for(var p=0;p<n;p++)try{d(g[m+p])}catch(t){throw new G(29);}n&&(f.node.timestamp=Date.now());return p}});return Pb(a,b,e)},bc=a=>{if(!(a.Se||a.zf||a.link||a.Hd)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(fa)try{a.Hd=$a(fa(a.url)),a.Ld=a.Hd.length}catch(b){throw new G(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");
}},cc=(a,b,c,d,e)=>{function f(n,p,t,q,u){n=n.node.Hd;if(u>=n.length)return 0;q=Math.min(n.length-u,q);if(n.slice)for(var x=0;x<q;x++)p[t+x]=n[u+x];else for(x=0;x<q;x++)p[t+x]=n.get(u+x);return q}if("undefined"!=typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";c={Se:!1,url:c};var g=ac(a,b,d,e);c.Hd?g.Hd=c.Hd:c.url&&(g.Hd=null,g.url=c.url);Object.defineProperties(g,{Ld:{get:function(){return this.Hd.length}}});
var m={};Object.keys(g.Jd).forEach(n=>{var p=g.Jd[n];m[n]=function(){bc(g);return p.apply(null,arguments)}});m.read=(n,p,t,q,u)=>{bc(g);return f(n,p,t,q,u)};m.Ee=(n,p,t)=>{bc(g);var q=hb(p);if(!q)throw new G(48);f(n,v,q,p,t);return{Bf:q,ff:!0}};g.Jd=m;return g},dc={},Mb,Tb,ec=void 0;function fc(){ec+=4;return y[ec-4>>2]}
function gc(a,b){hc=a;ic=b;if(jc)if(kc||(kc=!0),0==a)lc=function(){var d=Math.max(0,mc+b-nc())|0;setTimeout(oc,d)};else if(1==a)lc=function(){pc(oc)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}lc=function(){setImmediate(oc)}}}var nc;nc=()=>performance.now();
function qc(a,b,c,d,e){!jc||l("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");jc=a;rc=d;var f=sc;kc=!1;oc=function(){if(!ma)if(0<tc.length){var g=Date.now(),m=tc.shift();m.Wf(m.If);if(uc){var n=uc,p=0==n%1?n-1:Math.floor(n);uc=m.Rf?p:(8*n+(p+.5))/9}ja('main loop blocker "'+m.name+'" took '+(Date.now()-g)+" ms");h.setStatus&&(g=h.statusMessage||"Please wait...",
m=uc,n=vc.Uf,m?m<n?h.setStatus(g+" ("+(n-m)+"/"+n+")"):h.setStatus(g):h.setStatus(""));f<sc||setTimeout(oc,0)}else if(!(f<sc))if(wc=wc+1|0,1==hc&&1<ic&&0!=wc%ic)lc();else{0==hc&&(mc=nc());if(!(ma||h.preMainLoop&&!1===h.preMainLoop())){if(!ma)try{a(),xc()}catch(t){yc(t)}h.postMainLoop&&h.postMainLoop()}f<sc||("object"==typeof SDL&&SDL.audio&&SDL.audio.Cf&&SDL.audio.Cf(),lc())}};e||(b&&0<b?gc(0,1E3/b):gc(1,1),lc());if(c)throw"unwind";}
var yc=a=>{a instanceof Ma||"unwind"==a||da(1,a)},zc=a=>{na=a;if(!noExitRuntime){if(h.onExit)h.onExit(a);ma=!0}da(a,new Ma(a))},Ac=a=>{na=a;zc(a)},xc=()=>{if(!noExitRuntime)try{var a=na;na=a;zc(a)}catch(b){yc(b)}},Bc=a=>{setTimeout(()=>{if(!ma)try{a(),xc()}catch(b){yc(b)}},1E4)},kc=!1,lc=null,sc=0,jc=null,rc=0,hc=0,ic=0,wc=0,tc=[],vc={},mc,oc,uc,Cc=!1,Dc=!1,Ec=[];
function rb(){function a(){Dc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!Fc){Fc=!0;ob.push({canHandle:function(c){return!h.fg&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:Gc(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Gc(d)}));var m=URL.createObjectURL(g),n=new Image;n.onload=()=>{n.complete||l("Image "+
d+" could not be decoded");var p=document.createElement("canvas");p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(m);e&&e(c)};n.onerror=()=>{ja("Image "+m+" could not be decoded");f&&f()};n.src=m}});ob.push({canHandle:function(c){return!h.eg&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e&&e(c))}var g=!1,m=URL.createObjectURL(new Blob([c],{type:Gc(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);
n.onerror=function(){if(!g){k("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var p="",t=0,q=0,u=0;u<c.length;u++)for(t=t<<8|c[u],q+=8;6<=q;){var x=t>>q-6&63;q-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[x]}2==q?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&3)<<4],p+="=="):4==q&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&15)<<2],p+="=");n.src="data:audio/x-"+d.substr(-3)+
";base64,"+p;f(n)}};n.src=m;Bc(()=>{f(n)})}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",
a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!Dc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Hc(a,b,c,d){if(b&&h.Vd&&a==h.canvas)return h.Vd;var e;if(b){var f={antialias:!1,alpha:!1,Ue:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Ic&&(e=Jc(a,f)))var m=K[e].$d}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof L||l("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.Vd=m,b&&Kc(e),h.Gf=b,Ec.forEach(n=>n()),rb());return m}var Lc=!1,Mc=void 0,Nc=void 0;
function Oc(a,b){function c(){Cc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Pc,Mc&&d.requestPointerLock(),Cc=!0,Nc?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>2]|8388608),Qc(h.canvas),Rc()):Qc(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Nc?("undefined"!=typeof SDL&&(y[SDL.screen>>2]=z[SDL.screen>>2]&
-8388609),Qc(h.canvas),Rc()):Qc(d));if(h.onFullScreen)h.onFullScreen(Cc);if(h.onFullscreen)h.onFullscreen(Cc)}Mc=a;Nc=b;"undefined"==typeof Mc&&(Mc=!0);"undefined"==typeof Nc&&(Nc=!1);var d=h.canvas;Lc||(Lc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Pc(){if(!Cc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Sc=0;function pc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Sc)Sc=b+1E3/60;else for(;b+2>=Sc;)Sc+=1E3/60;setTimeout(a,Math.max(Sc-b,0))}}
function Gc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Tc=[];function Rc(){var a=h.canvas;Tc.forEach(b=>b(a.width,a.height))}
function Qc(a,b,c){b&&c?(a.Hf=b,a.sf=c):(b=a.Hf,c=a.sf);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Nc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var qb={},Fc,M=12288,Uc=!1,Vc=0,Wc=0,Xc=0,N={alpha:!1,depth:!1,stencil:!1,antialias:!1},Yc={},Zc;function $c(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function ad(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function bd(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var cd=1,dd=[],O=[],ed=[],fd=[],gd=[],Q=[],hd=[],K=[],jd=[],kd={},ld=4;
function R(a){md||(md=a)}function nd(a){for(var b=cd++,c=a.length;c<b;c++)a[c]=null;return b}function Jc(a,b){a.Nd||(a.Nd=a.getContext,a.getContext=function(d,e){e=a.Nd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?od(c,b):0}function od(a,b){var c=nd(K),d={handle:c,attributes:b,version:b.Ue,$d:a};a.canvas&&(a.canvas.ge=d);K[c]=d;("undefined"==typeof b.pf||b.pf)&&pd(d);return c}function Kc(a){qd=K[a];h.Vd=L=qd&&qd.$d}
function pd(a){a||(a=qd);if(!a.uf){a.uf=!0;var b=a.$d;$c(b);ad(b);bd(b);b.Xd=b.getExtension("EXT_disjoint_timer_query");b.cg=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var Ic={},md,qd,rd=a=>{var b=Za(a)+1,c=D(b);c&&E(a,w,c,b);return c},sd=[],td=(a,b)=>{sd.length=0;var c;for(b>>=2;c=w[a++];)b+=105!=c&b,sd.push(105==c?y[b]:(106==c?qa:B)[b++>>1]),++b;return sd},wd=a=>{var b=ud();a=a();vd(b);return a},xd=0;function yd(){for(var a=S.length-1;0<=a;--a)zd(a);S=[];T=[]}var T=[];
function Ad(a,b,c){function d(g,m){if(g.length!=m.length)return!1;for(var n in g)if(g[n]!=m[n])return!1;return!0}for(var e in T){var f=T[e];if(f.Ie==a&&d(f.Le,c))return}T.push({Ie:a,Ye:b,Le:c});T.sort(function(g,m){return g.Ye<m.Ye})}function Bd(a){for(var b=0;b<T.length;++b)T[b].Ie==a&&(T.splice(b,1),--b)}function Cd(){return navigator.userActivation?navigator.userActivation.isActive:xd&&Dd.he}function Ed(){if(Cd())for(var a=0;a<T.length;++a){var b=T[a];T.splice(a,1);--a;b.Ie.apply(null,b.Le)}}
var S=[];function zd(a){var b=S[a];b.target.removeEventListener(b.Od,b.qf,b.Sd);S.splice(a,1)}function U(a){function b(d){++xd;Dd=a;Ed();a.Ud(d);Ed();--xd}if(!a.target)return-4;if(a.Td)a.qf=b,a.target.addEventListener(a.Od,b,a.Sd),S.push(a),Fd||(ua.push(yd),Fd=!0);else for(var c=0;c<S.length;++c)S[c].target==a.target&&S[c].Od==a.Od&&zd(c--);return 0}function Gd(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
function Hd(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}var Id={},Fd,Dd,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd={},Wd=[0,document,window];function V(a){a=2<a?a?F(w,a):"":a;return Wd[a]||document.querySelector(a)}var Yd=a=>{var b=Za(a)+1,c=Xd(b);E(a,w,c,b);return c},Zd=a=>wd(()=>{var b=Xd(8),c=b+4,d=Yd(a.id);if(d=V(d))y[b>>2]=d.width,y[c>>2]=d.height;return[y[b>>2],y[c>>2]]});function $d(a,b,c){a=V(a);if(!a)return-4;a.width=b;a.height=c;return 0}
function ae(a,b,c){a.Qf?wd(function(){var d=Yd(a.id);$d(d,b,c)}):(a.width=b,a.height=c)}
function be(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),ae(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=t,a.style.paddingTop=q,a.style.paddingBottom=u,a.style.marginLeft=x,a.style.marginRight=P,a.style.marginTop=
X,a.style.marginBottom=Y,document.body.style.margin=vb,document.documentElement.style.overflow=Va,document.body.scroll=Me,a.style.ce=Ne,a.ge&&a.ge.$d.viewport(0,0,d,e),Vd.ne&&C.get(Vd.ne)(37,0,Vd.Me))}var c=Zd(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,t=a.style.paddingRight,q=a.style.paddingTop,u=a.style.paddingBottom,x=a.style.marginLeft,P=a.style.marginRight,X=a.style.marginTop,Y=a.style.marginBottom,vb=
document.body.style.margin,Va=document.documentElement.style.overflow,Me=document.body.scroll,Ne=a.style.ce;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function ce(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function de(a){return 0>Wd.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function ee(a,b){if(0!=b.He||0!=b.ze){be(a);var c=b.Ef?innerWidth:screen.width,d=b.Ef?innerHeight:screen.height,e=de(a),f=e.width;e=e.height;var g=Zd(a),m=g[0];g=g[1];3==b.He?(ce(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.He&&(c*g<m*d?(f=g*c/m,ce(a,(d-f)/2,0),d=f):(f=m*d/g,ce(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.rf&&(a.style.ce="optimizeSpeed",
a.style.ce="-moz-crisp-edges",a.style.ce="-o-crisp-edges",a.style.ce="-webkit-optimize-contrast",a.style.ce="optimize-contrast",a.style.ce="crisp-edges",a.style.ce="pixelated");f=2==b.ze?devicePixelRatio:1;0!=b.ze&&(c=c*f|0,d=d*f|0,ae(a,c,d),a.ge&&a.ge.$d.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Hd()?-3:-1;Vd=b;b.ne&&C.get(b.ne)(37,0,b.Me);return 0}
function fe(a){if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0}
function ge(a,b){B[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)B[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)B[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)y[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];y[a+1296>>2]=b.connected;y[a+1300>>2]=b.index;y[a+8>>2]=b.axes.length;y[a+12>>2]=b.buttons.length;E(b.id,w,a+1304,64);E(b.mapping,w,a+1368,64)}var he=[];
function ie(a,b,c,d){for(var e=0;e<a;e++){var f=L[c](),g=f&&nd(d);f?(f.name=g,d[g]=f):R(1282);y[b+4*e>>2]=g}}function je(a,b,c,d,e,f,g,m){b=O[b];if(a=L[a](b,c))d=m&&E(a.name,w,m,d),e&&(y[e>>2]=d),f&&(y[f>>2]=a.size),g&&(y[g>>2]=a.type)}function ke(a,b){z[a>>2]=b;z[a+4>>2]=(b-z[a>>2])/4294967296}
function le(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&R(1280);return;case 36345:d=0;break;case 34466:var e=L.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=L.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":R(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:R(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:y[b+4*a>>2]=e[a];break;case 2:A[b+4*a>>2]=e[a];break;case 4:v[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){R(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:R(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:ke(b,
d);break;case 0:y[b>>2]=d;break;case 2:A[b>>2]=d;break;case 4:v[b>>0]=d?1:0}}else R(1281)}function me(a,b,c){if(c){a=L.Xd.getQueryObjectEXT(jd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;ke(c,d)}else R(1281)}function ne(a,b,c){if(c){a=L.Xd.getQueryObjectEXT(jd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;y[c>>2]=d}else R(1281)}function oe(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}
function pe(a){var b=a.me,c=a.df,d;if(!b)for(a.me=b={},a.cf={},d=0;d<L.getProgramParameter(a,35718);++d){var e=L.getActiveUniform(a,d);var f=e.name;e=e.size;var g=oe(f);g=0<g?f.slice(0,g):f;var m=a.Je;a.Je+=e;c[g]=[e,m];for(f=0;f<e;++f)b[m]=f,a.cf[m++]=g}}function W(a){var b=L.jf;if(b){var c=b.me[a];"number"==typeof c&&(b.me[a]=c=L.getUniformLocation(b,b.cf[a]+(0<c?"["+c+"]":"")));return c}R(1282)}
function qe(a,b,c,d){if(c)if(a=O[a],pe(a),a=L.getUniform(a,W(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:y[c>>2]=a;break;case 2:A[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:y[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b]}else R(1281)}
function re(a,b,c,d){if(c)if(a=L.getVertexAttrib(a,b),34975==b)y[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:y[c>>2]=a;break;case 2:A[c>>2]=a;break;case 5:y[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:y[c+4*b>>2]=a[b];break;case 2:A[c+4*b>>2]=a[b];break;case 5:y[c+4*b>>2]=Math.fround(a[b])}else R(1281)}
function se(a,b,c,d,e){a-=5120;a=1==a?w:4==a?y:6==a?A:5==a||28922==a?z:pa;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=ld;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)}var te=[],ue=[];function ve(a,b){if(!Hd())return-1;a=V(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Cd()?ee(a,b):b.nf?(Ad(ee,1,[a,b]),1):-2:-3:-4}
function we(a,b){var c={target:V(2),Od:"beforeunload",Td:b,Ud:function(d=event){var e=C.get(b)(28,0,a);e&&(e=e?F(w,e):"");if(e)return d.preventDefault(),d.returnValue=e},Sd:!0};return U(c)}function xe(a,b,c,d,e,f){Kd||(Kd=D(256));a={target:V(a),Od:f,Td:d,Ud:function(g=event){var m=g.target.id?g.target.id:"",n=Kd;E(Gd(g.target),w,n+0,128);E(m,w,n+128,128);C.get(d)(e,n,b)&&g.preventDefault()},Sd:c};return U(a)}
function ye(a,b,c,d,e){Md||(Md=D(280));return U({target:a,Od:e,Td:d,Ud:function(f=event){var g=Md,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;y[g>>2]=n;y[g+4>>2]=Hd();var p=n?m:Ld,t=p&&p.id?p.id:"";E(Gd(p),w,g+8,128);E(t,w,g+136,128);y[g+264>>2]=p?p.clientWidth:0;y[g+268>>2]=p?p.clientHeight:0;y[g+272>>2]=screen.width;y[g+276>>2]=screen.height;n&&(Ld=m);C.get(d)(19,g,b)&&f.preventDefault()},Sd:c})}
function ze(a,b,c,d,e){Nd||(Nd=D(1432));b={target:V(2),he:!0,Od:e,Td:c,Ud:function(f=event){var g=Nd;ge(g,f.gamepad);C.get(c)(d,g,a)&&f.preventDefault()},Sd:b};return U(b)}
function Ae(a,b,c,d,e,f){Od||(Od=D(176));a={target:V(a),he:!0,Od:f,Td:d,Ud:function(g){var m=Od;B[m>>3]=g.timeStamp;var n=m>>2;y[n+2]=g.location;y[n+3]=g.ctrlKey;y[n+4]=g.shiftKey;y[n+5]=g.altKey;y[n+6]=g.metaKey;y[n+7]=g.repeat;y[n+8]=g.charCode;y[n+9]=g.keyCode;y[n+10]=g.which;E(g.key||"",w,m+44,32);E(g.code||"",w,m+76,32);E(g.char||"",w,m+108,32);E(g.locale||"",w,m+140,32);C.get(d)(e,m,b)&&g.preventDefault()},Sd:c};return U(a)}
function Be(a,b,c){B[a>>3]=b.timeStamp;a>>=2;y[a+2]=b.screenX;y[a+3]=b.screenY;y[a+4]=b.clientX;y[a+5]=b.clientY;y[a+6]=b.ctrlKey;y[a+7]=b.shiftKey;y[a+8]=b.altKey;y[a+9]=b.metaKey;oa[2*a+20]=b.button;oa[2*a+21]=b.buttons;y[a+11]=b.movementX;y[a+12]=b.movementY;c=de(c);y[a+13]=b.clientX-c.left;y[a+14]=b.clientY-c.top}
function Ce(a,b,c,d,e,f){Pd||(Pd=D(72));a=V(a);return U({target:a,he:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Od:f,Td:d,Ud:function(g=event){Be(Pd,g,a);C.get(d)(e,Pd,b)&&g.preventDefault()},Sd:c})}function De(a,b,c,d,e){Qd||(Qd=D(260));return U({target:a,Od:e,Td:d,Ud:function(f=event){var g=Qd,m=document.pointerLockElement||document.Nd||document.ef||document.ye;y[g>>2]=!!m;var n=m&&m.id?m.id:"";E(Gd(m),w,g+4,128);E(n,w,g+132,128);C.get(d)(20,g,b)&&f.preventDefault()},Sd:c})}
function Ee(a,b,c,d){Rd||(Rd=D(36));a=V(a);return U({target:a,Od:"resize",Td:d,Ud:function(e=event){if(e.target==a){var f=document.body;if(f){var g=Rd;y[g>>2]=e.detail;y[g+4>>2]=f.clientWidth;y[g+8>>2]=f.clientHeight;y[g+12>>2]=innerWidth;y[g+16>>2]=innerHeight;y[g+20>>2]=outerWidth;y[g+24>>2]=outerHeight;y[g+28>>2]=pageXOffset;y[g+32>>2]=pageYOffset;C.get(d)(10,g,b)&&e.preventDefault()}}},Sd:c})}
function Fe(a,b,c,d,e,f){Sd||(Sd=D(1696));a=V(a);return U({target:a,he:"touchstart"==f||"touchend"==f,Od:f,Td:d,Ud:function(g){for(var m,n={},p=g.touches,t=0;t<p.length;++t)m=p[t],m.Re=m.Xe=0,n[m.identifier]=m;for(t=0;t<g.changedTouches.length;++t)m=g.changedTouches[t],m.Re=1,n[m.identifier]=m;for(t=0;t<g.targetTouches.length;++t)n[g.targetTouches[t].identifier].Xe=1;p=Sd;B[p>>3]=g.timeStamp;var q=p>>2;y[q+3]=g.ctrlKey;y[q+4]=g.shiftKey;y[q+5]=g.altKey;y[q+6]=g.metaKey;q+=7;var u=de(a),x=0;for(t in n)if(m=
n[t],y[q]=m.identifier,y[q+1]=m.screenX,y[q+2]=m.screenY,y[q+3]=m.clientX,y[q+4]=m.clientY,y[q+5]=m.pageX,y[q+6]=m.pageY,y[q+7]=m.Re,y[q+8]=m.Xe,y[q+9]=m.clientX-u.left,y[q+10]=m.clientY-u.top,q+=13,31<++x)break;y[p+8>>2]=x;C.get(d)(e,p,b)&&g.preventDefault()},Sd:c})}
function Ge(a,b,c){var d=Wd[1];Td||(Td=D(8));return U({target:d,Od:"visibilitychange",Td:c,Ud:function(e=event){var f=Td,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);y[f>>2]=document.hidden;y[f+4>>2]=g;C.get(c)(21,f,a)&&e.preventDefault()},Sd:b})}
function He(a,b,c,d){Ud||(Ud=D(104));return U({target:a,he:!0,Od:"wheel",Td:d,Ud:function(e=event){var f=Ud;Be(f,e,a);B[f+72>>3]=e.deltaX;B[f+80>>3]=e.deltaY;B[f+88>>3]=e.deltaZ;y[f+96>>2]=e.deltaMode;C.get(d)(9,f,b)&&e.preventDefault()},Sd:c})}
var Ie={},Ke=()=>{if(!Je){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Ie)void 0===Ie[b]?delete a[b]:a[b]=Ie[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Je=c}return Je},Je;function Hb(a,b,c,d){a||(a=this);this.parent=a;this.Yd=a.Yd;this.je=null;this.id=zb++;this.name=b;this.mode=c;this.Id={};this.Jd={};this.ue=d}
Object.defineProperties(Hb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},zf:{get:function(){return 16384===(this.mode&61440)}},Se:{get:function(){return 8192===(this.mode&61440)}}});Yb();Ab=Array(4096);Ob(H,"/");I("/tmp",16895,0);I("/home",16895,0);I("/home/web_user",16895,0);
(()=>{I("/dev",16895,0);cb(259,{read:()=>0,write:(d,e,f,g)=>g});Pb("/dev/null",259);bb(1280,eb);bb(1536,fb);Pb("/dev/tty",1280);Pb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Ua(a).byteLength);return a[--b]};J("/dev","random",c);J("/dev","urandom",c);I("/dev/shm",16895,0);I("/dev/shm/tmp",16895,0)})();
(()=>{I("/proc",16895,0);var a=I("/proc/self",16895,0);I("/proc/self/fd",16895,0);Ob({Yd:()=>{var b=kb(a,"fd",16895,73);b.Id={ie:(c,d)=>{var e=Lb(+d);c={parent:null,Yd:{Ve:"fake"},Id:{ke:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=$b;h.FS_createDataFile=tb;h.FS_createPreloadedFile=sb;h.FS_unlink=Rb;h.FS_createLazyFile=cc;h.FS_createDevice=J;h.requestFullscreen=function(a,b){Oc(a,b)};h.requestAnimationFrame=function(a){pc(a)};
h.setCanvasSize=function(a,b,c){Qc(h.canvas,a,b);c||Rc()};h.pauseMainLoop=function(){lc=null;sc++};h.resumeMainLoop=function(){sc++;var a=hc,b=ic,c=jc;jc=null;qc(c,0,!1,rc,!0);gc(a,b);lc()};h.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=function(a,b,c,d){return Hc(a,b,c,d)};for(var L,Z=0;32>Z;++Z)he.push(Array(Z));var Le=new Float32Array(288);
for(Z=0;288>Z;++Z)te[Z]=Le.subarray(0,Z+1);var Oe=new Int32Array(288);for(Z=0;288>Z;++Z)ue[Z]=Oe.subarray(0,Z+1);
var Ue={H:function(a,b,c){ec=c;try{var d=Lb(a);switch(b){case 0:var e=fc();return 0>e?-28:Nb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=fc(),d.flags|=e,0;case 5:return e=fc(),oa[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return y[Pe()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof dc||"ErrnoError"!==f.name)throw f;return-f.ae}},Va:function(a,b,c){ec=c;try{var d=Lb(a);switch(b){case 21509:return d.Kd?0:-59;case 21505:if(!d.Kd)return-59;
if(d.Kd.Zd.wf){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=fc();y[e>>2]=25856;y[e+4>>2]=5;y[e+8>>2]=191;y[e+12>>2]=35387;for(var f=0;32>f;f++)v[e+f+17>>0]=b[f]||0}return 0;case 21510:case 21511:case 21512:return d.Kd?0:-59;case 21506:case 21507:case 21508:if(!d.Kd)return-59;if(d.Kd.Zd.xf)for(e=fc(),b=[],f=0;32>f;f++)b.push(v[e+f+17>>0]);return 0;case 21519:if(!d.Kd)return-59;e=fc();return y[e>>2]=0;case 21520:return d.Kd?-28:-59;case 21531:e=fc();if(!d.Jd.vf)throw new G(59);
return d.Jd.vf(d,b,e);case 21523:if(!d.Kd)return-59;d.Kd.Zd.yf&&(f=[24,80],e=fc(),oa[e>>1]=f[0],oa[e+2>>1]=f[1]);return 0;case 21524:return d.Kd?0:-59;case 21515:return d.Kd?0:-59;default:return-28}}catch(g){if("undefined"==typeof dc||"ErrnoError"!==g.name)throw g;return-g.ae}},Wa:function(a,b,c,d){ec=d;try{b=b?F(w,b):"";var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":Lb(a).path;if(0==e.length)throw new G(44);b=Qa(f+"/"+e)}var g=d?fc():0;return Ub(b,c,g).fd}catch(m){if("undefined"==typeof dc||
"ErrnoError"!==m.name)throw m;return-m.ae}},Xa:()=>!0,Na:()=>{throw Infinity;},Hb:function(a){if(12448==a)return M=12288,1;M=12300;return 0},wc:function(a,b,c,d,e){if(62E3!=a)M=12296,c=0;else{if(b)for(;;){a=y[b>>2];if(12321==a)N.alpha=0<y[b+4>>2];else if(12325==a)N.depth=0<y[b+4>>2];else if(12326==a)N.stencil=0<y[b+4>>2];else if(12337==a)a=y[b+4>>2],N.antialias=0<a;else if(12338==a)a=y[b+4>>2],N.antialias=1==a;else if(12544==a)N.$f=12547!=y[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(y[e>>2]=
1),c&&0<d&&(y[c>>2]=62002),M=12288,c=1):(M=12300,c=0)}return c},Ia:function(a,b,c,d){if(62E3!=a)return M=12296,0;for(a=1;;){b=y[d>>2];if(12440==b)a=y[d+4>>2];else if(12344==b)break;else return M=12292,0;d+=8}if(2!=a)return M=12293,0;N.Ue=a-1;N.ag=0;Zc=Jc(h.canvas,N);if(0!=Zc)return M=12288,Kc(Zc),h.Gf=!0,Ec.forEach(function(e){e()}),Kc(null),62004;M=12297;return 0},Ka:function(a,b){if(62E3!=a)return M=12296,0;if(62002!=b)return M=12293,0;M=12288;return 62006},Ja:function(a,b){if(62E3!=a)return M=
12296,0;if(62004!=b)return M=12294,0;a=Zc;qd===K[a]&&(qd=null);if("object"==typeof Id)for(var c=K[a].$d.canvas,d=0;d<S.length;++d)S[d].target!=c||zd(d--);K[a]&&K[a].$d.canvas&&(K[a].$d.canvas.ge=void 0);K[a]=null;M=12288;Vc==b&&(Vc=0);return 1},La:function(a,b){if(62E3!=a)return M=12296,0;if(62006!=b)return M=12301,1;Wc==b&&(Wc=0);Xc==b&&(Xc=0);M=12288;return 1},Hc:function(a,b,c,d){if(62E3!=a)return M=12296,0;if(62002!=b)return M=12293,0;if(!d)return M=12300,0;M=12288;switch(c){case 12320:return y[d>>
2]=N.alpha?32:24,1;case 12321:return y[d>>2]=N.alpha?8:0,1;case 12322:return y[d>>2]=8,1;case 12323:return y[d>>2]=8,1;case 12324:return y[d>>2]=8,1;case 12325:return y[d>>2]=N.depth?24:0,1;case 12326:return y[d>>2]=N.stencil?8:0,1;case 12327:return y[d>>2]=12344,1;case 12328:return y[d>>2]=62002,1;case 12329:return y[d>>2]=0,1;case 12330:return y[d>>2]=4096,1;case 12331:return y[d>>2]=16777216,1;case 12332:return y[d>>2]=4096,1;case 12333:return y[d>>2]=0,1;case 12334:return y[d>>2]=0,1;case 12335:return y[d>>
2]=12344,1;case 12337:return y[d>>2]=N.antialias?4:0,1;case 12338:return y[d>>2]=N.antialias?1:0,1;case 12339:return y[d>>2]=4,1;case 12340:return y[d>>2]=12344,1;case 12341:case 12342:case 12343:return y[d>>2]=-1,1;case 12345:case 12346:return y[d>>2]=0,1;case 12347:return y[d>>2]=0,1;case 12348:return y[d>>2]=1;case 12349:case 12350:return y[d>>2]=0,1;case 12351:return y[d>>2]=12430,1;case 12352:return y[d>>2]=4,1;case 12354:return y[d>>2]=0,1;default:return M=12292,0}},J:function(){M=12288;return 62E3},
Ha:function(){return M},ac:function(a,b,c){if(62E3!=a)return M=12296,0;b&&(y[b>>2]=1);c&&(y[c>>2]=4);Uc=!0;M=12288;return 1},Ma:function(a,b,c,d){if(62E3!=a)return M=12296,0;if(0!=d&&62004!=d)return M=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return M=12301,0;Kc(d?Zc:null);Vc=d;Xc=b;Wc=c;M=12288;return 1},Fa:function(a,b){if(62E3!=a)return M=12296,0;M=12288;if(Yc[b])return Yc[b];switch(b){case 12371:a=rd("Emscripten");break;case 12372:a=rd("1.4 Emscripten EGL");break;case 12373:a=rd("");break;case 12429:a=
rd("OpenGL_ES");break;default:return M=12300,0}return Yc[b]=a},Ua:function(){if(Uc)if(h.Vd)if(h.Vd.isContextLost())M=12302;else return M=12288,1;else M=12290;else M=12289;return 0},$a:function(a,b){if(62E3!=a)return M=12296,0;0==b?gc(0,0):gc(1,b);M=12288;return 1},lc:function(a){if(62E3!=a)return M=12296,0;Xc=Wc=Vc=0;Uc=!1;M=12288;return 1},vb:function(){M=12288;return 1},kb:function(){M=12288;return 1},Ba:(a,b,c)=>{b=td(b,c);return La[a].apply(null,b)},a:(a,b,c)=>{b=td(b,c);return La[a].apply(null,
b)},e:function(){return Date.now()},ya:function(){if(!Hd())return-1;Bd(ee);var a=Wd[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Da:function(){Bd(fe);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},d:function(){return devicePixelRatio},b:function(a,b,c){a=V(a);if(!a)return-4;a=de(a);B[b>>3]=a.width;B[c>>3]=a.height;return 0},j:function(a,b){if(0>
a||a>=Jd.length)return-5;if(!Jd[a])return-7;ge(b,Jd[a]);return 0},Pa:()=>w.length,g:nc,ea:function(){return Jd.length},Ea:function(a,b){y[a>>2]=screen.width;y[b>>2]=screen.height},da:function(a){L.activeTexture(a)},ca:function(a,b){L.attachShader(O[a],Q[b])},ua:function(a,b){L.Xd.beginQueryEXT(a,jd[b])},ba:function(a,b,c){L.bindAttribLocation(O[a],b,c?F(w,c):"")},aa:function(a,b){L.bindBuffer(a,dd[b])},$:function(a,b){L.bindFramebuffer(a,ed[b])},_:function(a,b){L.bindRenderbuffer(a,fd[b])},Z:function(a,
b){L.bindTexture(a,gd[b])},ma:function(a){L.bindVertexArray(hd[a])},Y:function(a,b,c,d){L.blendColor(a,b,c,d)},X:function(a){L.blendEquation(a)},W:function(a,b){L.blendEquationSeparate(a,b)},V:function(a,b){L.blendFunc(a,b)},U:function(a,b,c,d){L.blendFuncSeparate(a,b,c,d)},T:function(a,b,c,d){L.bufferData(a,c?w.subarray(c,c+b):b,d)},S:function(a,b,c,d){L.bufferSubData(a,b,w.subarray(d,d+c))},R:function(a){return L.checkFramebufferStatus(a)},Q:function(a){L.clear(a)},P:function(a,b,c,d){L.clearColor(a,
b,c,d)},O:function(a){L.clearDepth(a)},N:function(a){L.clearStencil(a)},M:function(a,b,c,d){L.colorMask(!!a,!!b,!!c,!!d)},td:function(a){L.compileShader(Q[a])},sd:function(a,b,c,d,e,f,g,m){L.compressedTexImage2D(a,b,c,d,e,f,m?w.subarray(m,m+g):null)},rd:function(a,b,c,d,e,f,g,m,n){L.compressedTexSubImage2D(a,b,c,d,e,f,g,n?w.subarray(n,n+m):null)},qd:function(a,b,c,d,e,f,g,m){L.copyTexImage2D(a,b,c,d,e,f,g,m)},pd:function(a,b,c,d,e,f,g,m){L.copyTexSubImage2D(a,b,c,d,e,f,g,m)},od:function(){var a=nd(O),
b=L.createProgram();b.name=a;b.re=b.pe=b.qe=0;b.Je=1;O[a]=b;return a},nd:function(a){var b=nd(Q);Q[b]=L.createShader(a);return b},md:function(a){L.cullFace(a)},ld:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=dd[d];e&&(L.deleteBuffer(e),e.name=0,dd[d]=null)}},kd:function(a,b){for(var c=0;c<a;++c){var d=y[b+4*c>>2],e=ed[d];e&&(L.deleteFramebuffer(e),e.name=0,ed[d]=null)}},jd:function(a){if(a){var b=O[a];b?(L.deleteProgram(b),b.name=0,O[a]=null):R(1281)}},wa:function(a,b){for(var c=0;c<a;c++){var d=
y[b+4*c>>2],e=jd[d];e&&(L.Xd.deleteQueryEXT(e),jd[d]=null)}},id:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=fd[d];e&&(L.deleteRenderbuffer(e),e.name=0,fd[d]=null)}},hd:function(a){if(a){var b=Q[a];b?(L.deleteShader(b),Q[a]=null):R(1281)}},gd:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2],e=gd[d];e&&(L.deleteTexture(e),e.name=0,gd[d]=null)}},la:function(a,b){for(var c=0;c<a;c++){var d=y[b+4*c>>2];L.deleteVertexArray(hd[d]);hd[d]=null}},fd:function(a){L.depthFunc(a)},ed:function(a){L.depthMask(!!a)},
dd:function(a,b){L.depthRange(a,b)},cd:function(a,b){L.detachShader(O[a],Q[b])},bd:function(a){L.disable(a)},ad:function(a){L.disableVertexAttribArray(a)},$c:function(a,b,c){L.drawArrays(a,b,c)},ha:function(a,b,c,d){L.drawArraysInstanced(a,b,c,d)},ia:function(a,b){for(var c=he[a],d=0;d<a;d++)c[d]=y[b+4*d>>2];L.drawBuffers(c)},_c:function(a,b,c,d){L.drawElements(a,b,c,d)},ga:function(a,b,c,d,e){L.drawElementsInstanced(a,b,c,d,e)},Zc:function(a){L.enable(a)},Yc:function(a){L.enableVertexAttribArray(a)},
ta:function(a){L.Xd.endQueryEXT(a)},Xc:function(){L.finish()},Wc:function(){L.flush()},Vc:function(a,b,c,d){L.framebufferRenderbuffer(a,b,c,fd[d])},Uc:function(a,b,c,d,e){L.framebufferTexture2D(a,b,c,gd[d],e)},Tc:function(a){L.frontFace(a)},Sc:function(a,b){ie(a,b,"createBuffer",dd)},Qc:function(a,b){ie(a,b,"createFramebuffer",ed)},xa:function(a,b){for(var c=0;c<a;c++){var d=L.Xd.createQueryEXT();if(!d){for(R(1282);c<a;)y[b+4*c++>>2]=0;break}var e=nd(jd);d.name=e;jd[e]=d;y[b+4*c>>2]=e}},Pc:function(a,
b){ie(a,b,"createRenderbuffer",fd)},Oc:function(a,b){ie(a,b,"createTexture",gd)},ka:function(a,b){ie(a,b,"createVertexArray",hd)},Rc:function(a){L.generateMipmap(a)},Nc:function(a,b,c,d,e,f,g){je("getActiveAttrib",a,b,c,d,e,f,g)},Mc:function(a,b,c,d,e,f,g){je("getActiveUniform",a,b,c,d,e,f,g)},Lc:function(a,b,c,d){a=L.getAttachedShaders(O[a]);var e=a.length;e>b&&(e=b);y[c>>2]=e;for(b=0;b<e;++b)y[d+4*b>>2]=Q.indexOf(a[b])},Kc:function(a,b){return L.getAttribLocation(O[a],b?F(w,b):"")},Jc:function(a,
b){le(a,b,4)},Ic:function(a,b,c){c?y[c>>2]=L.getBufferParameter(a,b):R(1281)},Gc:function(){var a=L.getError()||md;md=0;return a},Fc:function(a,b){le(a,b,2)},Ec:function(a,b,c,d){a=L.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;y[d>>2]=a},Dc:function(a,b){le(a,b,0)},Bc:function(a,b,c,d){a=L.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,w,d,b):0;c&&(y[c>>2]=b)},Cc:function(a,b,c){if(c)if(a>=cd)R(1281);else if(a=
O[a],35716==b)a=L.getProgramInfoLog(a),null===a&&(a="(unknown error)"),y[c>>2]=a.length+1;else if(35719==b){if(!a.re)for(b=0;b<L.getProgramParameter(a,35718);++b)a.re=Math.max(a.re,L.getActiveUniform(a,b).name.length+1);y[c>>2]=a.re}else if(35722==b){if(!a.pe)for(b=0;b<L.getProgramParameter(a,35721);++b)a.pe=Math.max(a.pe,L.getActiveAttrib(a,b).name.length+1);y[c>>2]=a.pe}else if(35381==b){if(!a.qe)for(b=0;b<L.getProgramParameter(a,35382);++b)a.qe=Math.max(a.qe,L.getActiveUniformBlockName(a,b).length+
1);y[c>>2]=a.qe}else y[c>>2]=L.getProgramParameter(a,b);else R(1281)},oa:me,qa:ne,na:me,pa:ne,ra:function(a,b,c){c?y[c>>2]=L.Xd.getQueryEXT(a,b):R(1281)},Ac:function(a,b,c){c?y[c>>2]=L.getRenderbufferParameter(a,b):R(1281)},yc:function(a,b,c,d){a=L.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,w,d,b):0;c&&(y[c>>2]=b)},xc:function(a,b,c,d){a=L.getShaderPrecisionFormat(a,b);y[c>>2]=a.rangeMin;y[c+4>>2]=a.rangeMax;y[d>>2]=a.precision},vc:function(a,b,c,d){if(a=L.getShaderSource(Q[a]))b=
0<b&&d?E(a,w,d,b):0,c&&(y[c>>2]=b)},zc:function(a,b,c){c?35716==b?(a=L.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),y[c>>2]=a?a.length+1:0):35720==b?(a=L.getShaderSource(Q[a]),y[c>>2]=a?a.length+1:0):y[c>>2]=L.getShaderParameter(Q[a],b):R(1281)},uc:function(a){var b=kd[a];if(!b){switch(a){case 7939:b=L.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=rd(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=L.getParameter(a))||R(1280);b=b&&rd(b);break;
case 7938:b=rd("OpenGL ES 2.0 ("+L.getParameter(7938)+")");break;case 35724:b=L.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=rd(b);break;default:R(1280)}kd[a]=b}return b},tc:function(a,b,c){c?A[c>>2]=L.getTexParameter(a,b):R(1281)},sc:function(a,b,c){c?y[c>>2]=L.getTexParameter(a,b):R(1281)},pc:function(a,b){b=b?F(w,b):"";if(a=O[a]){pe(a);var c=a.me,d=0,e=b,f=oe(b);0<f&&(d=parseInt(b.slice(f+
1))>>>0,e=b.slice(0,f));if((e=a.df[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||L.getUniformLocation(a,b)))return d}else R(1281);return-1},rc:function(a,b,c){qe(a,b,c,2)},qc:function(a,b,c){qe(a,b,c,0)},mc:function(a,b,c){c?y[c>>2]=L.getVertexAttribOffset(a,b):R(1281)},oc:function(a,b,c){re(a,b,c,2)},nc:function(a,b,c){re(a,b,c,5)},kc:function(a,b){L.hint(a,b)},jc:function(a){return(a=dd[a])?L.isBuffer(a):0},ic:function(a){return L.isEnabled(a)},hc:function(a){return(a=ed[a])?L.isFramebuffer(a):0},gc:function(a){return(a=
O[a])?L.isProgram(a):0},va:function(a){return(a=jd[a])?L.Xd.isQueryEXT(a):0},fc:function(a){return(a=fd[a])?L.isRenderbuffer(a):0},ec:function(a){return(a=Q[a])?L.isShader(a):0},dc:function(a){return(a=gd[a])?L.isTexture(a):0},ja:function(a){return(a=hd[a])?L.isVertexArray(a):0},cc:function(a){L.lineWidth(a)},bc:function(a){a=O[a];L.linkProgram(a);a.me=0;a.df={}},$b:function(a,b){3317==a&&(ld=b);L.pixelStorei(a,b)},_b:function(a,b){L.polygonOffset(a,b)},sa:function(a,b){L.Xd.queryCounterEXT(jd[a],
b)},Zb:function(a,b,c,d,e,f,g){(g=se(f,e,c,d,g))?L.readPixels(a,b,c,d,e,f,g):R(1280)},Yb:function(){},Xb:function(a,b,c,d){L.renderbufferStorage(a,b,c,d)},Wb:function(a,b){L.sampleCoverage(a,!!b)},Vb:function(a,b,c,d){L.scissor(a,b,c,d)},Ub:function(){R(1280)},Tb:function(a,b,c,d){for(var e="",f=0;f<b;++f){var g=d?y[d+4*f>>2]:-1,m=y[c+4*f>>2];g=m?F(w,m,0>g?void 0:g):"";e+=g}L.shaderSource(Q[a],e)},Sb:function(a,b,c){L.stencilFunc(a,b,c)},Rb:function(a,b,c,d){L.stencilFuncSeparate(a,b,c,d)},Qb:function(a){L.stencilMask(a)},
Pb:function(a,b){L.stencilMaskSeparate(a,b)},Ob:function(a,b,c){L.stencilOp(a,b,c)},Nb:function(a,b,c,d){L.stencilOpSeparate(a,b,c,d)},Mb:function(a,b,c,d,e,f,g,m,n){L.texImage2D(a,b,c,d,e,f,g,m,n?se(m,g,d,e,n):null)},Lb:function(a,b,c){L.texParameterf(a,b,c)},Kb:function(a,b,c){L.texParameterf(a,b,A[c>>2])},Jb:function(a,b,c){L.texParameteri(a,b,c)},Ib:function(a,b,c){L.texParameteri(a,b,y[c>>2])},Gb:function(a,b,c,d,e,f,g,m,n){var p=null;n&&(p=se(m,g,e,f,n));L.texSubImage2D(a,b,c,d,e,f,g,m,p)},
Fb:function(a,b){L.uniform1f(W(a),b)},Eb:function(a,b,c){if(288>=b)for(var d=te[b-1],e=0;e<b;++e)d[e]=A[c+4*e>>2];else d=A.subarray(c>>2,c+4*b>>2);L.uniform1fv(W(a),d)},Db:function(a,b){L.uniform1i(W(a),b)},Cb:function(a,b,c){if(288>=b)for(var d=ue[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);L.uniform1iv(W(a),d)},Bb:function(a,b,c){L.uniform2f(W(a),b,c)},Ab:function(a,b,c){if(144>=b)for(var d=te[2*b-1],e=0;e<2*b;e+=2)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2];else d=A.subarray(c>>
2,c+8*b>>2);L.uniform2fv(W(a),d)},zb:function(a,b,c){L.uniform2i(W(a),b,c)},yb:function(a,b,c){if(144>=b)for(var d=ue[2*b-1],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);L.uniform2iv(W(a),d)},xb:function(a,b,c,d){L.uniform3f(W(a),b,c,d)},ub:function(a,b,c){if(96>=b)for(var d=te[3*b-1],e=0;e<3*b;e+=3)d[e]=A[c+4*e>>2],d[e+1]=A[c+(4*e+4)>>2],d[e+2]=A[c+(4*e+8)>>2];else d=A.subarray(c>>2,c+12*b>>2);L.uniform3fv(W(a),d)},tb:function(a,b,c,d){L.uniform3i(W(a),
b,c,d)},sb:function(a,b,c){if(96>=b)for(var d=ue[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);L.uniform3iv(W(a),d)},rb:function(a,b,c,d,e){L.uniform4f(W(a),b,c,d,e)},qb:function(a,b,c){if(72>=b){var d=te[4*b-1],e=A;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=A.subarray(c>>2,c+16*b>>2);L.uniform4fv(W(a),d)},pb:function(a,b,c,d,e){L.uniform4i(W(a),b,c,d,e)},ob:function(a,
b,c){if(72>=b)for(var d=ue[4*b-1],e=0;e<4*b;e+=4)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2],d[e+3]=y[c+(4*e+12)>>2];else d=y.subarray(c>>2,c+16*b>>2);L.uniform4iv(W(a),d)},nb:function(a,b,c,d){if(72>=b)for(var e=te[4*b-1],f=0;f<4*b;f+=4)e[f]=A[d+4*f>>2],e[f+1]=A[d+(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2];else e=A.subarray(d>>2,d+16*b>>2);L.uniformMatrix2fv(W(a),!!c,e)},mb:function(a,b,c,d){if(32>=b)for(var e=te[9*b-1],f=0;f<9*b;f+=9)e[f]=A[d+4*f>>2],e[f+1]=A[d+
(4*f+4)>>2],e[f+2]=A[d+(4*f+8)>>2],e[f+3]=A[d+(4*f+12)>>2],e[f+4]=A[d+(4*f+16)>>2],e[f+5]=A[d+(4*f+20)>>2],e[f+6]=A[d+(4*f+24)>>2],e[f+7]=A[d+(4*f+28)>>2],e[f+8]=A[d+(4*f+32)>>2];else e=A.subarray(d>>2,d+36*b>>2);L.uniformMatrix3fv(W(a),!!c,e)},lb:function(a,b,c,d){if(18>=b){var e=te[16*b-1],f=A;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+
11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=A.subarray(d>>2,d+64*b>>2);L.uniformMatrix4fv(W(a),!!c,e)},jb:function(a){a=O[a];L.useProgram(a);L.jf=a},ib:function(a){L.validateProgram(O[a])},hb:function(a,b){L.vertexAttrib1f(a,b)},gb:function(a,b){L.vertexAttrib1f(a,A[b>>2])},fb:function(a,b,c){L.vertexAttrib2f(a,b,c)},eb:function(a,b){L.vertexAttrib2f(a,A[b>>2],A[b+4>>2])},db:function(a,b,c,d){L.vertexAttrib3f(a,b,c,d)},cb:function(a,b){L.vertexAttrib3f(a,A[b>>2],A[b+
4>>2],A[b+8>>2])},bb:function(a,b,c,d,e){L.vertexAttrib4f(a,b,c,d,e)},ab:function(a,b){L.vertexAttrib4f(a,A[b>>2],A[b+4>>2],A[b+8>>2],A[b+12>>2])},fa:function(a,b){L.vertexAttribDivisor(a,b)},_a:function(a,b,c,d,e,f){L.vertexAttribPointer(a,b,c,!!d,e,f)},Za:function(a,b,c,d){L.viewport(a,b,c,d)},i:()=>0,Ya:(a,b,c)=>w.copyWithin(a,b,b+c),za:function(a,b,c){return ve(a,{He:y[c>>2],ze:y[c+4>>2],rf:y[c+8>>2],nf:b,ne:y[c+12>>2],Me:y[c+16>>2]})},F:function(a,b){a=V(a);return a?a.requestPointerLock?Cd()?
fe(a):b?(Ad(fe,2,[a]),1):-2:-1:-4},Oa:()=>{l("OOM")},k:function(){return(Jd=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},l:function(a,b,c){return"undefined"==typeof onbeforeunload?-1:1!==c?-5:we(a,b)},x:function(a,b,c,d){return xe(a,b,c,d,12,"blur")},c:$d,f:function(a,b,c){a=V(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},y:function(a,b,c,d){return xe(a,b,c,d,13,"focus")},o:function(a,b,c,d){if(!Hd())return-1;
a=V(a);if(!a)return-4;ye(a,b,c,d,"webkitfullscreenchange");return ye(a,b,c,d,"fullscreenchange")},L:function(a,b,c){return navigator.getGamepads||navigator.webkitGetGamepads?ze(a,b,c,26,"gamepadconnected"):-1},K:function(a,b,c){return navigator.getGamepads||navigator.webkitGetGamepads?ze(a,b,c,27,"gamepaddisconnected"):-1},r:function(a,b,c,d){return Ae(a,b,c,d,2,"keydown")},p:function(a,b,c,d){return Ae(a,b,c,d,1,"keypress")},q:function(a,b,c,d){return Ae(a,b,c,d,3,"keyup")},vd:function(a,b,c){a=
C.get(a);qc(a,b,c)},D:function(a,b,c,d){return Ce(a,b,c,d,5,"mousedown")},B:function(a,b,c,d){return Ce(a,b,c,d,33,"mouseenter")},A:function(a,b,c,d){return Ce(a,b,c,d,34,"mouseleave")},E:function(a,b,c,d){return Ce(a,b,c,d,8,"mousemove")},C:function(a,b,c,d){return Ce(a,b,c,d,6,"mouseup")},s:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Nd||document.body.ef||document.body.ye))return-1;a=V(a);if(!a)return-4;De(a,b,c,d,"mozpointerlockchange");De(a,
b,c,d,"webkitpointerlockchange");De(a,b,c,d,"mspointerlockchange");return De(a,b,c,d,"pointerlockchange")},n:function(a,b,c,d){return Ee(a,b,c,d)},t:function(a,b,c,d){return Fe(a,b,c,d,25,"touchcancel")},v:function(a,b,c,d){return Fe(a,b,c,d,23,"touchend")},u:function(a,b,c,d){return Fe(a,b,c,d,24,"touchmove")},w:function(a,b,c,d){return Fe(a,b,c,d,22,"touchstart")},m:function(a,b,c){return Ge(a,b,c)},z:function(a,b,c,d){return(a=V(a))?"undefined"!=typeof a.onwheel?He(a,b,c,d):-1:-4},Aa:function(a){ia(a?
F(w,a):"")},h:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Ra:(a,b)=>{var c=0;Ke().forEach(function(d,e){var f=b+c;e=z[a+4*e>>2]=f;for(f=0;f<d.length;++f)v[e++>>0]=d.charCodeAt(f);v[e>>0]=0;c+=d.length+1});return 0},Sa:(a,b)=>{var c=Ke();z[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});z[b>>2]=d;return 0},I:function(a){try{var b=Lb(a);Vb(b);return 0}catch(c){if("undefined"==typeof dc||"ErrnoError"!==
c.name)throw c;return c.ae}},Ta:function(a,b,c,d){try{a:{var e=Lb(a);a=b;for(var f,g=b=0;g<c;g++){var m=z[a>>2],n=z[a+4>>2];a+=8;var p=e,t=m,q=n,u=f,x=v;if(0>q||0>u)throw new G(28);if(null===p.fd)throw new G(8);if(1===(p.flags&2097155))throw new G(8);if(16384===(p.node.mode&61440))throw new G(31);if(!p.Jd.read)throw new G(28);var P="undefined"!=typeof u;if(!P)u=p.position;else if(!p.seekable)throw new G(70);var X=p.Jd.read(p,x,t,q,u);P||(p.position+=X);var Y=X;if(0>Y){var vb=-1;break a}b+=Y;if(Y<
n)break;"undefined"!==typeof f&&(f+=Y)}vb=b}z[d>>2]=vb;return 0}catch(Va){if("undefined"==typeof dc||"ErrnoError"!==Va.name)throw Va;return Va.ae}},Qa:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);try{if(isNaN(b))return 61;var e=Lb(a);Wb(e,b,c);qa[d>>3]=BigInt(e.position);e.De&&0===b&&0===c&&(e.De=null);return 0}catch(f){if("undefined"==typeof dc||"ErrnoError"!==f.name)throw f;return f.ae}},G:function(a,b,c,d){try{a:{var e=
Lb(a);a=b;for(var f,g=b=0;g<c;g++){var m=z[a>>2],n=z[a+4>>2];a+=8;var p=Xb(e,v,m,n,f);if(0>p){var t=-1;break a}b+=p;"undefined"!==typeof f&&(f+=p)}t=b}z[d>>2]=t;return 0}catch(q){if("undefined"==typeof dc||"ErrnoError"!==q.name)throw q;return q.ae}},ud:Qe,Ga:Re,wb:Se,Ca:Te};
(function(){function a(c){r=c=c.exports;la=r.wd;var d=la.buffer;h.HEAP8=v=new Int8Array(d);h.HEAP16=oa=new Int16Array(d);h.HEAP32=y=new Int32Array(d);h.HEAPU8=w=new Uint8Array(d);h.HEAPU16=pa=new Uint16Array(d);h.HEAPU32=z=new Uint32Array(d);h.HEAPF32=A=new Float32Array(d);h.HEAPF64=B=new Float64Array(d);h.HEAP64=qa=new BigInt64Array(d);h.HEAPU64=new BigUint64Array(d);C=r.yd;sa.unshift(r.xd);Ba("wasm-instantiate");return c}var b={a:Ue};Aa("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,
a)}catch(c){return k("Module.instantiateWasm callback failed with error: "+c),!1}Ia(b,function(c){a(c.instance)});return{}})();var Ve=h._main=(a,b)=>(Ve=h._main=r.zd)(a,b),D=a=>(D=r.Ad)(a),Pe=()=>(Pe=r.Bd)(),gb=(a,b)=>(gb=r.Cd)(a,b),We=(a,b)=>(We=r.Dd)(a,b),ud=()=>(ud=r.Ed)(),vd=a=>(vd=r.Fd)(a),Xd=a=>(Xd=r.Gd)(a);function Qe(a,b,c){var d=ud();try{return C.get(a)(b,c)}catch(e){vd(d);if(e!==e+0)throw e;We(1,0)}}
function Se(a,b,c,d,e){var f=ud();try{return C.get(a)(b,c,d,e)}catch(g){vd(f);if(g!==g+0)throw g;We(1,0)}}function Re(a,b,c,d){var e=ud();try{return C.get(a)(b,c,d)}catch(f){vd(e);if(f!==f+0)throw f;We(1,0)}}function Te(a,b){var c=ud();try{C.get(a)(b)}catch(d){vd(c);if(d!==d+0)throw d;We(1,0)}}h.addRunDependency=Aa;h.removeRunDependency=Ba;h.FS_createPath=$b;h.FS_createDataFile=tb;h.FS_createLazyFile=cc;h.FS_createDevice=J;h.FS_unlink=Rb;h.FS_createPreloadedFile=sb;var Xe;
za=function Ye(){Xe||Ze();Xe||(za=Ye)};function $e(a=[]){var b=Ve;a.unshift(ca);var c=a.length,d=Xd(4*(c+1)),e=d>>2;a.forEach(g=>{y[e++]=Yd(g)});y[e]=0;try{var f=b(c,d);Ac(f)}catch(g){yc(g)}}
function Ze(){var a=ba;function b(){if(!Xe&&(Xe=!0,h.calledRun=!0,!ma)){h.noFSInit||Zb||(Zb=!0,Yb(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?J("/dev","stdin",h.stdin):Qb("/dev/tty","/dev/stdin"),h.stdout?J("/dev","stdout",null,h.stdout):Qb("/dev/tty","/dev/stdout"),h.stderr?J("/dev","stderr",null,h.stderr):Qb("/dev/tty1","/dev/stderr"),Ub("/dev/stdin",0),Ub("/dev/stdout",1),Ub("/dev/stderr",1));Bb=!1;Oa(sa);Oa(ta);if(h.onRuntimeInitialized)h.onRuntimeInitialized();af&&$e(a);if(h.postRun)for("function"==
typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();va.unshift(c)}Oa(va)}}if(!(0<xa)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)wa();Oa(ra);0<xa||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var af=!0;h.noInitialRun&&(af=!1);Ze();
