var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},h),ba=[],ca="./this.program",da=(a,b)=>{throw b;},k="",ea;"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);k=0!==k.indexOf("blob:")?k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1):"";ea=a=>{document.title=a};var fa=h.print||console.log.bind(console),l=h.printErr||console.error.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);
h.thisProgram&&(ca=h.thisProgram);h.quit&&(da=h.quit);var ha;h.wasmBinary&&(ha=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!1;"object"!=typeof WebAssembly&&ia("no native wasm support detected");var ja,p,q=!1,ka,t,u,la,ma,x,y,z,na,A,B,oa=[],pa=[],qa=[],ra=[],sa=[],ta=!1,C=0;function ua(){var a=h.preRun.shift();oa.unshift(a)}var D=0,va=null,wa=null;
function ia(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";l(a);q=!0;ka=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function xa(a){return a.startsWith("data:application/octet-stream;base64,")}var E;E="tetrism.wasm";if(!xa(E)){var ya=E;E=h.locateFile?h.locateFile(ya,k):k+ya}function za(a){if(a==E&&ha)return new Uint8Array(ha);throw"both async and sync fetching of the wasm failed";}
function Aa(a){return ha||"function"!=typeof fetch?Promise.resolve().then(()=>za(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>za(a))}function Ba(a,b,c){return Aa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{l("failed to asynchronously prepare wasm: "+d);ia(d)})}
function Ca(a,b){var c=E;ha||"function"!=typeof WebAssembly.instantiateStreaming||xa(c)||"function"!=typeof fetch?Ba(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){l("wasm streaming compile failed: "+e);l("falling back to ArrayBuffer instantiation");return Ba(c,a,b)}))}
var Fa={281328:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,281475:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,281709:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.g||("undefined"!==typeof AudioContext?b.g=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.g=new webkitAudioContext),b.g&&Da(b.g));
return void 0===b.g?-1:0},282202:()=>h.SDL2.g.sampleRate,282270:(a,b,c,d)=>{function e(){}function f(m){void 0!==g.capture.C&&(clearTimeout(g.capture.C),g.capture.C=void 0);g.capture.K=g.g.createMediaStreamSource(m);g.capture.i=g.g.createScriptProcessor(b,a,1);g.capture.i.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.N=n.inputBuffer,n=[d],B.get(c).apply(null,n))};g.capture.K.connect(g.capture.i);g.capture.i.connect(g.g.destination);
g.capture.stream=m}var g=h.SDL2;g.capture.L=g.g.createBuffer(a,b,g.g.sampleRate);g.capture.L.getChannelData(0).fill(0);g.capture.C=setTimeout(function(){g.capture.N=g.capture.L;var m=[d];B.get(c).apply(null,m)},b/g.g.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},283922:(a,b,c,d)=>{var e=
h.SDL2;e.audio.i=e.g.createScriptProcessor(b,0,a);e.audio.i.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.U=f.outputBuffer,f=[d],B.get(c).apply(null,f))};e.audio.i.connect(e.g.destination)},284332:(a,b)=>{for(var c=h.SDL2,d=c.capture.N.numberOfChannels,e=0;e<d;++e){var f=c.capture.N.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Ea(a+4*g,f[g]);else for(g=
0;g<b;++g)Ea(a+4*(g*d+e),f[g])}},284937:(a,b)=>{for(var c=h.SDL2,d=c.audio.U.numberOfChannels,e=0;e<d;++e){var f=c.audio.U.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=z[a+(g*d+e<<2)>>2]}},285417:a=>{var b=h.SDL2;if(a){void 0!==b.capture.C&&clearTimeout(b.capture.C);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.i&&(b.capture.i.onaudioprocess=function(){},b.capture.i.disconnect(),b.capture.i=void 0);void 0!==b.capture.K&&(b.capture.K.disconnect(),b.capture.K=void 0);void 0!==b.capture.L&&(b.capture.L=void 0);b.capture=void 0}else void 0!=b.audio.i&&(b.audio.i.disconnect(),b.audio.i=void 0),b.audio=void 0;void 0!==b.g&&void 0===b.audio&&void 0===b.capture&&(b.g.close(),b.g=void 0)},286589:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.aa!==h.canvas&&(d.o=h.createContext(h.canvas,
!1,!0),d.aa=h.canvas);if(d.w!==a||d.ja!==b||d.ma!==d.o)d.image=d.o.createImageData(a,b),d.w=a,d.ja=b,d.ma=d.o;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=x[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.da!==a&&(d.ca=new Int32Array(a.buffer),d.ea=new Uint8Array(a.buffer),d.da=a),a=d.ca,c=a.length,a.set(x.subarray(b,b+c)),a=d.ea,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=
b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.o.putImageData(d.image,0,0)},288058:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var r=x[e];b[m]=r&255;b[m+1]=r>>8&255;b[m+2]=r>>16&255;b[m+3]=r>>24&255;e++;m+=4}else b=
new Int32Array(b.buffer),n=b.length,b.set(x.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=F(c.length+1);G(c,d,c.length+1);return d},289047:a=>{h.canvas&&(h.canvas.style.cursor=a?H(u,a):"")},289130:()=>{h.canvas&&(h.canvas.style.cursor="none")},289199:()=>window.innerWidth,289229:()=>window.innerHeight};function Ga(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}
var Ha=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Da=a=>{var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Ha(d,c,()=>{"suspended"===a.state&&a.resume()})})})},I=a=>{for(;0<a.length;)a.shift()(h)};
function Ea(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":t[a>>0]=b;break;case "i8":t[a>>0]=b;break;case "i16":la[a>>1]=b;break;case "i32":x[a>>2]=b;break;case "i64":na[a>>3]=BigInt(b);break;case "float":z[a>>2]=b;break;case "double":A[a>>3]=b;break;case "*":y[a>>2]=b;break;default:ia(`invalid type for setValue: ${c}`)}}
var Ia=(a,b)=>{for(var c=0;c<a.length;++c)t[b++>>0]=a.charCodeAt(c);t[b>>0]=0},Ja="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,H=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ja)return Ja.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ka;Ka=()=>performance.now();
function La(a,b){Ma=a;Na=b;if(Oa)if(Pa||(C+=1,Pa=!0),0==a)J=function(){var d=Math.max(0,Qa+b-Ka())|0;setTimeout(Ra,d)};else if(1==a)J=function(){Ua(Ra)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}J=function(){setImmediate(Ra)}}}
var Va=a=>{ka=a;if(!(noExitRuntime||0<C)){if(h.onExit)h.onExit(a);q=!0}da(a,new Ga(a))},Wa=a=>{a instanceof Ga||"unwind"==a||da(1,a)},Ya=()=>{if(!(ta||noExitRuntime||0<C))try{var a=ka;ka=a;noExitRuntime||0<C||(I(ra),Xa(),ta=!0);Va(a)}catch(b){Wa(b)}};
function Za(a,b,c,d,e){function f(){return g<$a?(--C,Ya(),!1):!0}!Oa||ia("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Oa=a;ab=d;var g=$a;Pa=!1;Ra=function(){if(!q)if(0<bb.length){var m=Date.now(),n=bb.shift();n.xa(n.ta);if(cb){var r=cb,w=0==r%1?r-1:Math.floor(r);cb=n.va?w:(8*r+(w+.5))/9}fa('main loop blocker "'+n.name+'" took '+(Date.now()-m)+" ms");h.setStatus&&
(m=h.statusMessage||"Please wait...",n=cb,r=db.wa,n?n<r?h.setStatus(m+" ("+(r-n)+"/"+r+")"):h.setStatus(m):h.setStatus(""));f()&&setTimeout(Ra,0)}else if(f())if(eb=eb+1|0,1==Ma&&1<Na&&0!=eb%Na)J();else{0==Ma&&(Qa=Ka());if(!(q||h.preMainLoop&&!1===h.preMainLoop())){if(!ta&&!q)try{a(),Ya()}catch(v){Wa(v)}h.postMainLoop&&h.postMainLoop()}f()&&("object"==typeof SDL&&SDL.audio&&SDL.audio.pa&&SDL.audio.pa(),J())}};e||(b&&0<b?La(0,1E3/b):La(1,1),J());if(c)throw"unwind";}
var Pa=!1,J=null,$a=0,Oa=null,ab=0,Ma=0,Na=0,eb=0,bb=[],db={},Qa,Ra,cb,fb=!1,gb=!1,hb=[];
function ib(){function a(){gb=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!jb){jb=!0;var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),
b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!gb&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function kb(a,b,c,d){if(b&&h.o&&a==h.canvas)return h.o;var e;if(b){var f={antialias:!1,alpha:!1,W:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof lb&&(e=mb(a,f)))var m=K[e].u}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof L||ia("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.o=m,b&&nb(e),h.ra=b,hb.forEach(n=>n()),ib());return m}var ob=!1,pb=void 0,qb=void 0;
function rb(a,b){function c(){fb=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=sb,pb&&d.requestPointerLock(),fb=!0,qb?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]|8388608),tb(h.canvas),ub()):tb(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),qb?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]&
-8388609),tb(h.canvas),ub()):tb(d));if(h.onFullScreen)h.onFullScreen(fb);if(h.onFullscreen)h.onFullscreen(fb)}pb=a;qb=b;"undefined"==typeof pb&&(pb=!0);"undefined"==typeof qb&&(qb=!1);var d=h.canvas;ob||(ob=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function sb(){if(!fb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var vb=0;function Ua(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===vb)vb=b+1E3/60;else for(;b+2>=vb;)vb+=1E3/60;setTimeout(a,Math.max(vb-b,0))}}var wb=[];function ub(){var a=h.canvas;wb.forEach(b=>b(a.width,a.height))}
function tb(a,b,c){b&&c?(a.sa=b,a.ka=c):(b=a.sa,c=a.ka);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}qb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var jb,M=12288,xb=!1,yb=0,zb=0,Ab=0,N={alpha:!1,depth:!1,stencil:!1,antialias:!1},Bb={},Cb;function Db(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function Eb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Fb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Gb=1,Hb=[],O=[],Ib=[],Jb=[],Kb=[],P=[],Lb=[],K=[],Q=[],Mb={},Nb=4;
function R(a){Ob||(Ob=a)}function Pb(a){for(var b=Gb++,c=a.length;c<b;c++)a[c]=null;return b}function mb(a,b){a.G||(a.G=a.getContext,a.getContext=function(d,e){e=a.G(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Qb(c,b):0}function Qb(a,b){var c=Pb(K),d={handle:c,attributes:b,version:b.W,u:a};a.canvas&&(a.canvas.A=d);K[c]=d;("undefined"==typeof b.ga||b.ga)&&Rb(d);return c}function nb(a){Sb=K[a];h.o=L=Sb&&Sb.u}
function Rb(a){a||(a=Sb);if(!a.na){a.na=!0;var b=a.u;Db(b);Eb(b);Fb(b);b.s=b.getExtension("EXT_disjoint_timer_query");b.Aa=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var lb={},Ob,Sb,Tb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},G=(a,b,c)=>{var d=u;if(!(0<c))return 0;var e=b;c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=
128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0;return b-e},S=a=>{var b=Tb(a)+1,c=F(b);c&&G(a,c,b);return c},Ub=[],Vb=(a,b)=>{Ub.length=0;var c;for(b>>=2;c=u[a++];)b+=105!=c&b,Ub.push(105==c?x[b]:(106==c?na:A)[b++>>1]),++b;return Ub},Yb=a=>{var b=Wb();a=a();Xb(b);return a},Zb=0;function $b(){for(var a=T.length-1;0<=a;--a)ac(a);T=[];U=[]}var U=[];
function bc(a,b,c){function d(g,m){if(g.length!=m.length)return!1;for(var n in g)if(g[n]!=m[n])return!1;return!0}for(var e in U){var f=U[e];if(f.P==a&&d(f.S,c))return}U.push({P:a,Y:b,S:c});U.sort(function(g,m){return g.Y<m.Y})}function cc(a){for(var b=0;b<U.length;++b)U[b].P==a&&(U.splice(b,1),--b)}function dc(){return navigator.userActivation?navigator.userActivation.isActive:Zb&&ec.B}function fc(){if(dc())for(var a=0;a<U.length;++a){var b=U[a];U.splice(a,1);--a;b.P.apply(null,b.S)}}var T=[];
function ac(a){var b=T[a];b.target.removeEventListener(b.h,b.ha,b.j);T.splice(a,1)}function V(a){function b(d){++Zb;ec=a;fc();a.m(d);fc();--Zb}if(!a.target)return-4;if(a.l)a.ha=b,a.target.addEventListener(a.h,b,a.j),T.push(a),gc||(ra.push($b),gc=!0);else for(var c=0;c<T.length;++c)T[c].target==a.target&&T[c].h==a.h&&ac(c--);return 0}function hc(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
function ic(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}var jc={},gc,ec,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc={},xc=[0,document,window];function W(a){a=2<a?a?H(u,a):"":a;return xc[a]||document.querySelector(a)}var zc=a=>{var b=Tb(a)+1,c=yc(b);G(a,c,b);return c},Ac=a=>Yb(()=>{var b=yc(8),c=b+4,d=zc(a.id);if(d=W(d))x[b>>2]=d.width,x[c>>2]=d.height;return[x[b>>2],x[c>>2]]});function Bc(a,b,c){a=W(a);if(!a)return-4;a.width=b;a.height=c;return 0}
function Cc(a,b,c){a.ua?Yb(function(){var d=zc(a.id);Bc(d,b,c)}):(a.width=b,a.height=c)}
function Dc(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Cc(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=r,a.style.paddingRight=w,a.style.paddingTop=v,a.style.paddingBottom=Sa,a.style.marginLeft=Ta,a.style.marginRight=qd,a.style.marginTop=
rd,a.style.marginBottom=sd,document.body.style.margin=td,document.documentElement.style.overflow=ud,document.body.scroll=vd,a.style.v=wd,a.A&&a.A.u.viewport(0,0,d,e),wc.F&&B.get(wc.F)(37,0,wc.T))}var c=Ac(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,r=a.style.paddingLeft,w=a.style.paddingRight,v=a.style.paddingTop,Sa=a.style.paddingBottom,Ta=a.style.marginLeft,qd=a.style.marginRight,rd=a.style.marginTop,sd=a.style.marginBottom,td=
document.body.style.margin,ud=document.documentElement.style.overflow,vd=document.body.scroll,wd=a.style.v;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function Ec(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function Fc(a){return 0>xc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Gc(a,b){if(0!=b.O||0!=b.M){Dc(a);var c=b.qa?innerWidth:screen.width,d=b.qa?innerHeight:screen.height,e=Fc(a),f=e.width;e=e.height;var g=Ac(a),m=g[0];g=g[1];3==b.O?(Ec(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.O&&(c*g<m*d?(f=g*c/m,Ec(a,(d-f)/2,0),d=f):(f=m*d/g,Ec(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.ia&&(a.style.v="optimizeSpeed",
a.style.v="-moz-crisp-edges",a.style.v="-o-crisp-edges",a.style.v="-webkit-optimize-contrast",a.style.v="optimize-contrast",a.style.v="crisp-edges",a.style.v="pixelated");f=2==b.M?devicePixelRatio:1;0!=b.M&&(c=c*f|0,d=d*f|0,Cc(a,c,d),a.A&&a.A.u.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return ic()?-3:-1;wc=b;b.F&&B.get(b.F)(37,0,b.T);return 0}
function Hc(a){if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0}
function Ic(a,b){A[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)A[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)A[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)x[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];x[a+1296>>2]=b.connected;x[a+1300>>2]=b.index;x[a+8>>2]=b.axes.length;x[a+12>>2]=b.buttons.length;G(b.id,a+1304,64);G(b.mapping,a+1368,64)}var Jc=[];
function Kc(a,b,c,d){for(var e=0;e<a;e++){var f=L[c](),g=f&&Pb(d);f?(f.name=g,d[g]=f):R(1282);x[b+4*e>>2]=g}}function Lc(a,b,c,d,e,f,g,m){b=O[b];if(a=L[a](b,c))d=m&&G(a.name,m,d),e&&(x[e>>2]=d),f&&(x[f>>2]=a.size),g&&(x[g>>2]=a.type)}function Mc(a,b){y[a>>2]=b;y[a+4>>2]=(b-y[a>>2])/4294967296}
function Nc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&R(1280);return;case 36345:d=0;break;case 34466:var e=L.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=L.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":R(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:R(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:x[b+4*a>>2]=e[a];break;case 2:z[b+4*a>>2]=e[a];break;case 4:t[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){R(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:R(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Mc(b,
d);break;case 0:x[b>>2]=d;break;case 2:z[b>>2]=d;break;case 4:t[b>>0]=d?1:0}}else R(1281)}function Oc(a,b,c){if(c){a=L.s.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Mc(c,d)}else R(1281)}function Pc(a,b,c){if(c){a=L.s.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else R(1281)}function Qc(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}
function Rc(a){var b=a.D,c=a.$,d;if(!b)for(a.D=b={},a.Z={},d=0;d<L.getProgramParameter(a,35718);++d){var e=L.getActiveUniform(a,d);var f=e.name;e=e.size;var g=Qc(f);g=0<g?f.slice(0,g):f;var m=a.R;a.R+=e;c[g]=[e,m];for(f=0;f<e;++f)b[m]=f,a.Z[m++]=g}}function X(a){var b=L.ba;if(b){var c=b.D[a];"number"==typeof c&&(b.D[a]=c=L.getUniformLocation(b,b.Z[a]+(0<c?"["+c+"]":"")));return c}R(1282)}
function Sc(a,b,c,d){if(c)if(a=O[a],Rc(a),a=L.getUniform(a,X(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:z[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b]}else R(1281)}
function Tc(a,b,c,d){if(c)if(a=L.getVertexAttrib(a,b),34975==b)x[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:z[c>>2]=a;break;case 5:x[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b];break;case 5:x[c+4*b>>2]=Math.fround(a[b])}else R(1281)}
function Uc(a,b,c,d,e){a-=5120;a=1==a?u:4==a?x:6==a?z:5==a||28922==a?y:ma;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=Nb;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)}var Y=[],Vc=[];function Wc(a,b){if(!ic())return-1;a=W(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?dc()?Gc(a,b):b.fa?(bc(Gc,1,[a,b]),1):-2:-3:-4}
function Xc(a,b){var c={target:W(2),h:"beforeunload",l:b,m:function(d=event){var e=B.get(b)(28,0,a);e&&(e=e?H(u,e):"");if(e)return d.preventDefault(),d.returnValue=e},j:!0};return V(c)}function Yc(a,b,c,d,e,f){lc||(lc=F(256));a={target:W(a),h:f,l:d,m:function(g=event){var m=g.target.id?g.target.id:"",n=lc;G(hc(g.target),n+0,128);G(m,n+128,128);B.get(d)(e,n,b)&&g.preventDefault()},j:c};return V(a)}
function Zc(a,b,c,d,e){nc||(nc=F(280));return V({target:a,h:e,l:d,m:function(f=event){var g=nc,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;x[g>>2]=n;x[g+4>>2]=ic();var r=n?m:mc,w=r&&r.id?r.id:"";G(hc(r),g+8,128);G(w,g+136,128);x[g+264>>2]=r?r.clientWidth:0;x[g+268>>2]=r?r.clientHeight:0;x[g+272>>2]=screen.width;x[g+276>>2]=screen.height;n&&(mc=m);B.get(d)(19,g,b)&&f.preventDefault()},j:c})}
function $c(a,b,c,d,e){oc||(oc=F(1432));b={target:W(2),B:!0,h:e,l:c,m:function(f=event){var g=oc;Ic(g,f.gamepad);B.get(c)(d,g,a)&&f.preventDefault()},j:b};return V(b)}
function ad(a,b,c,d,e,f){pc||(pc=F(176));a={target:W(a),B:!0,h:f,l:d,m:function(g){var m=pc;A[m>>3]=g.timeStamp;var n=m>>2;x[n+2]=g.location;x[n+3]=g.ctrlKey;x[n+4]=g.shiftKey;x[n+5]=g.altKey;x[n+6]=g.metaKey;x[n+7]=g.repeat;x[n+8]=g.charCode;x[n+9]=g.keyCode;x[n+10]=g.which;G(g.key||"",m+44,32);G(g.code||"",m+76,32);G(g.char||"",m+108,32);G(g.locale||"",m+140,32);B.get(d)(e,m,b)&&g.preventDefault()},j:c};return V(a)}
function bd(a,b,c){A[a>>3]=b.timeStamp;a>>=2;x[a+2]=b.screenX;x[a+3]=b.screenY;x[a+4]=b.clientX;x[a+5]=b.clientY;x[a+6]=b.ctrlKey;x[a+7]=b.shiftKey;x[a+8]=b.altKey;x[a+9]=b.metaKey;la[2*a+20]=b.button;la[2*a+21]=b.buttons;x[a+11]=b.movementX;x[a+12]=b.movementY;c=Fc(c);x[a+13]=b.clientX-c.left;x[a+14]=b.clientY-c.top}
function cd(a,b,c,d,e,f){qc||(qc=F(72));a=W(a);return V({target:a,B:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,h:f,l:d,m:function(g=event){bd(qc,g,a);B.get(d)(e,qc,b)&&g.preventDefault()},j:c})}function dd(a,b,c,d,e){rc||(rc=F(260));return V({target:a,h:e,l:d,m:function(f=event){var g=rc,m=document.pointerLockElement||document.G||document.oa||document.la;x[g>>2]=!!m;var n=m&&m.id?m.id:"";G(hc(m),g+4,128);G(n,g+132,128);B.get(d)(20,g,b)&&f.preventDefault()},j:c})}
function ed(a,b,c,d){sc||(sc=F(36));a=W(a);return V({target:a,h:"resize",l:d,m:function(e=event){if(e.target==a){var f=document.body;if(f){var g=sc;x[g>>2]=e.detail;x[g+4>>2]=f.clientWidth;x[g+8>>2]=f.clientHeight;x[g+12>>2]=innerWidth;x[g+16>>2]=innerHeight;x[g+20>>2]=outerWidth;x[g+24>>2]=outerHeight;x[g+28>>2]=pageXOffset;x[g+32>>2]=pageYOffset;B.get(d)(10,g,b)&&e.preventDefault()}}},j:c})}
function fd(a,b,c,d,e,f){tc||(tc=F(1696));a=W(a);return V({target:a,B:"touchstart"==f||"touchend"==f,h:f,l:d,m:function(g){for(var m,n={},r=g.touches,w=0;w<r.length;++w)m=r[w],m.V=m.X=0,n[m.identifier]=m;for(w=0;w<g.changedTouches.length;++w)m=g.changedTouches[w],m.V=1,n[m.identifier]=m;for(w=0;w<g.targetTouches.length;++w)n[g.targetTouches[w].identifier].X=1;r=tc;A[r>>3]=g.timeStamp;var v=r>>2;x[v+3]=g.ctrlKey;x[v+4]=g.shiftKey;x[v+5]=g.altKey;x[v+6]=g.metaKey;v+=7;var Sa=Fc(a),Ta=0;for(w in n)if(m=
n[w],x[v]=m.identifier,x[v+1]=m.screenX,x[v+2]=m.screenY,x[v+3]=m.clientX,x[v+4]=m.clientY,x[v+5]=m.pageX,x[v+6]=m.pageY,x[v+7]=m.V,x[v+8]=m.X,x[v+9]=m.clientX-Sa.left,x[v+10]=m.clientY-Sa.top,v+=13,31<++Ta)break;x[r+8>>2]=Ta;B.get(d)(e,r,b)&&g.preventDefault()},j:c})}
function gd(a,b,c){var d=xc[1];uc||(uc=F(8));return V({target:d,h:"visibilitychange",l:c,m:function(e=event){var f=uc,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);x[f>>2]=document.hidden;x[f+4>>2]=g;B.get(c)(21,f,a)&&e.preventDefault()},j:b})}
function hd(a,b,c,d){vc||(vc=F(104));return V({target:a,B:!0,h:"wheel",l:d,m:function(e=event){var f=vc;bd(f,e,a);A[f+72>>3]=e.deltaX;A[f+80>>3]=e.deltaY;A[f+88>>3]=e.deltaZ;x[f+96>>2]=e.deltaMode;B.get(d)(9,f,b)&&e.preventDefault()},j:c})}
var jd={},ld=()=>{if(!kd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in jd)void 0===jd[b]?delete a[b]:a[b]=jd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);kd=c}return kd},kd,md=[null,[],[]],nd=(a,b)=>{var c=md[a];0===b||10===b?((1===a?fa:l)(H(c,0)),c.length=0):c.push(b)},Xa=()=>{md[1].length&&nd(1,10);md[2].length&&nd(2,
10)};h.requestFullscreen=function(a,b){rb(a,b)};h.requestAnimationFrame=function(a){Ua(a)};h.setCanvasSize=function(a,b,c){tb(h.canvas,a,b);c||ub()};h.pauseMainLoop=function(){J=null;$a++};h.resumeMainLoop=function(){$a++;var a=Ma,b=Na,c=Oa;Oa=null;Za(c,0,!1,ab,!0);La(a,b);J()};h.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=function(a,b,c,d){return kb(a,b,c,d)};for(var L,Z=0;32>Z;++Z)Jc.push(Array(Z));
var od=new Float32Array(288);for(Z=0;288>Z;++Z)Y[Z]=od.subarray(0,Z+1);var pd=new Int32Array(288);for(Z=0;288>Z;++Z)Vc[Z]=pd.subarray(0,Z+1);
var Cd={_emscripten_throw_longjmp:()=>{throw Infinity;},args_get:(a,b)=>{var c=0;xd.forEach(function(d,e){var f=b+c;y[a+4*e>>2]=f;Ia(d,f);c+=d.length+1});return 0},args_sizes_get:(a,b)=>{y[a>>2]=xd.length;var c=0;xd.forEach(function(d){c+=d.length+1});y[b>>2]=c;return 0},clock_time_get:function(a,b,c){c=-9007199254740992>c||9007199254740992<c?NaN:Number(c);if(0!=a&&1!=a&&2!=a&&3!=a)return 28;var d;0===a?d=Date.now():d=Ka();a=Math.round(1E6*d);x[c>>2]=a>>>0;x[c+4>>2]=a/Math.pow(2,32)>>>0;return 0},
eglBindAPI:function(a){if(12448==a)return M=12288,1;M=12300;return 0},eglChooseConfig:function(a,b,c,d,e){if(62E3!=a)M=12296,c=0;else{if(b)for(;;){a=x[b>>2];if(12321==a)N.alpha=0<x[b+4>>2];else if(12325==a)N.depth=0<x[b+4>>2];else if(12326==a)N.stencil=0<x[b+4>>2];else if(12337==a)a=x[b+4>>2],N.antialias=0<a;else if(12338==a)a=x[b+4>>2],N.antialias=1==a;else if(12544==a)N.ya=12547!=x[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(x[e>>2]=1),c&&0<d&&(x[c>>2]=62002),M=12288,c=1):(M=12300,c=0)}return c},
eglCreateContext:function(a,b,c,d){if(62E3!=a)return M=12296,0;for(a=1;;){b=x[d>>2];if(12440==b)a=x[d+4>>2];else if(12344==b)break;else return M=12292,0;d+=8}if(2!=a)return M=12293,0;N.W=a-1;N.za=0;Cb=mb(h.canvas,N);if(0!=Cb)return M=12288,nb(Cb),h.ra=!0,hb.forEach(function(e){e()}),nb(null),62004;M=12297;return 0},eglCreateWindowSurface:function(a,b){if(62E3!=a)return M=12296,0;if(62002!=b)return M=12293,0;M=12288;return 62006},eglDestroyContext:function(a,b){if(62E3!=a)return M=12296,0;if(62004!=
b)return M=12294,0;a=Cb;Sb===K[a]&&(Sb=null);if("object"==typeof jc)for(var c=K[a].u.canvas,d=0;d<T.length;++d)T[d].target!=c||ac(d--);K[a]&&K[a].u.canvas&&(K[a].u.canvas.A=void 0);K[a]=null;M=12288;yb==b&&(yb=0);return 1},eglDestroySurface:function(a,b){if(62E3!=a)return M=12296,0;if(62006!=b)return M=12301,1;zb==b&&(zb=0);Ab==b&&(Ab=0);M=12288;return 1},eglGetConfigAttrib:function(a,b,c,d){if(62E3!=a)return M=12296,0;if(62002!=b)return M=12293,0;if(!d)return M=12300,0;M=12288;switch(c){case 12320:return x[d>>
2]=N.alpha?32:24,1;case 12321:return x[d>>2]=N.alpha?8:0,1;case 12322:return x[d>>2]=8,1;case 12323:return x[d>>2]=8,1;case 12324:return x[d>>2]=8,1;case 12325:return x[d>>2]=N.depth?24:0,1;case 12326:return x[d>>2]=N.stencil?8:0,1;case 12327:return x[d>>2]=12344,1;case 12328:return x[d>>2]=62002,1;case 12329:return x[d>>2]=0,1;case 12330:return x[d>>2]=4096,1;case 12331:return x[d>>2]=16777216,1;case 12332:return x[d>>2]=4096,1;case 12333:return x[d>>2]=0,1;case 12334:return x[d>>2]=0,1;case 12335:return x[d>>
2]=12344,1;case 12337:return x[d>>2]=N.antialias?4:0,1;case 12338:return x[d>>2]=N.antialias?1:0,1;case 12339:return x[d>>2]=4,1;case 12340:return x[d>>2]=12344,1;case 12341:case 12342:case 12343:return x[d>>2]=-1,1;case 12345:case 12346:return x[d>>2]=0,1;case 12347:return x[d>>2]=0,1;case 12348:return x[d>>2]=1;case 12349:case 12350:return x[d>>2]=0,1;case 12351:return x[d>>2]=12430,1;case 12352:return x[d>>2]=4,1;case 12354:return x[d>>2]=0,1;default:return M=12292,0}},eglGetDisplay:function(){M=
12288;return 62E3},eglGetError:function(){return M},eglInitialize:function(a,b,c){if(62E3!=a)return M=12296,0;b&&(x[b>>2]=1);c&&(x[c>>2]=4);xb=!0;M=12288;return 1},eglMakeCurrent:function(a,b,c,d){if(62E3!=a)return M=12296,0;if(0!=d&&62004!=d)return M=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return M=12301,0;nb(d?Cb:null);yb=d;Ab=b;zb=c;M=12288;return 1},eglQueryString:function(a,b){if(62E3!=a)return M=12296,0;M=12288;if(Bb[b])return Bb[b];switch(b){case 12371:a=S("Emscripten");break;case 12372:a=
S("1.4 Emscripten EGL");break;case 12373:a=S("");break;case 12429:a=S("OpenGL_ES");break;default:return M=12300,0}return Bb[b]=a},eglSwapBuffers:function(){if(xb)if(h.o)if(h.o.isContextLost())M=12302;else return M=12288,1;else M=12290;else M=12289;return 0},eglSwapInterval:function(a,b){if(62E3!=a)return M=12296,0;0==b?La(0,0):La(1,b);M=12288;return 1},eglTerminate:function(a){if(62E3!=a)return M=12296,0;Ab=zb=yb=0;xb=!1;M=12288;return 1},eglWaitGL:function(){M=12288;return 1},eglWaitNative:function(){M=
12288;return 1},emscripten_asm_const_int:(a,b,c)=>{b=Vb(b,c);return Fa[a].apply(null,b)},emscripten_asm_const_int_sync_on_main_thread:(a,b,c)=>{b=Vb(b,c);return Fa[a].apply(null,b)},emscripten_exit_fullscreen:function(){if(!ic())return-1;cc(Gc);var a=xc[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},emscripten_exit_pointerlock:function(){cc(Hc);if(document.exitPointerLock)document.exitPointerLock();
else return-1;return 0},emscripten_get_device_pixel_ratio:function(){return devicePixelRatio},emscripten_get_element_css_size:function(a,b,c){a=W(a);if(!a)return-4;a=Fc(a);A[b>>3]=a.width;A[c>>3]=a.height;return 0},emscripten_get_gamepad_status:function(a,b){if(0>a||a>=kc.length)return-5;if(!kc[a])return-7;Ic(b,kc[a]);return 0},emscripten_get_num_gamepads:function(){return kc.length},emscripten_get_screen_size:function(a,b){x[a>>2]=screen.width;x[b>>2]=screen.height},emscripten_glActiveTexture:function(a){L.activeTexture(a)},
emscripten_glAttachShader:function(a,b){L.attachShader(O[a],P[b])},emscripten_glBeginQueryEXT:function(a,b){L.s.beginQueryEXT(a,Q[b])},emscripten_glBindAttribLocation:function(a,b,c){L.bindAttribLocation(O[a],b,c?H(u,c):"")},emscripten_glBindBuffer:function(a,b){L.bindBuffer(a,Hb[b])},emscripten_glBindFramebuffer:function(a,b){L.bindFramebuffer(a,Ib[b])},emscripten_glBindRenderbuffer:function(a,b){L.bindRenderbuffer(a,Jb[b])},emscripten_glBindTexture:function(a,b){L.bindTexture(a,Kb[b])},emscripten_glBindVertexArrayOES:function(a){L.bindVertexArray(Lb[a])},
emscripten_glBlendColor:function(a,b,c,d){L.blendColor(a,b,c,d)},emscripten_glBlendEquation:function(a){L.blendEquation(a)},emscripten_glBlendEquationSeparate:function(a,b){L.blendEquationSeparate(a,b)},emscripten_glBlendFunc:function(a,b){L.blendFunc(a,b)},emscripten_glBlendFuncSeparate:function(a,b,c,d){L.blendFuncSeparate(a,b,c,d)},emscripten_glBufferData:function(a,b,c,d){L.bufferData(a,c?u.subarray(c,c+b):b,d)},emscripten_glBufferSubData:function(a,b,c,d){L.bufferSubData(a,b,u.subarray(d,d+c))},
emscripten_glCheckFramebufferStatus:function(a){return L.checkFramebufferStatus(a)},emscripten_glClear:function(a){L.clear(a)},emscripten_glClearColor:function(a,b,c,d){L.clearColor(a,b,c,d)},emscripten_glClearDepthf:function(a){L.clearDepth(a)},emscripten_glClearStencil:function(a){L.clearStencil(a)},emscripten_glColorMask:function(a,b,c,d){L.colorMask(!!a,!!b,!!c,!!d)},emscripten_glCompileShader:function(a){L.compileShader(P[a])},emscripten_glCompressedTexImage2D:function(a,b,c,d,e,f,g,m){L.compressedTexImage2D(a,
b,c,d,e,f,m?u.subarray(m,m+g):null)},emscripten_glCompressedTexSubImage2D:function(a,b,c,d,e,f,g,m,n){L.compressedTexSubImage2D(a,b,c,d,e,f,g,n?u.subarray(n,n+m):null)},emscripten_glCopyTexImage2D:function(a,b,c,d,e,f,g,m){L.copyTexImage2D(a,b,c,d,e,f,g,m)},emscripten_glCopyTexSubImage2D:function(a,b,c,d,e,f,g,m){L.copyTexSubImage2D(a,b,c,d,e,f,g,m)},emscripten_glCreateProgram:function(){var a=Pb(O),b=L.createProgram();b.name=a;b.J=b.H=b.I=0;b.R=1;O[a]=b;return a},emscripten_glCreateShader:function(a){var b=
Pb(P);P[b]=L.createShader(a);return b},emscripten_glCullFace:function(a){L.cullFace(a)},emscripten_glDeleteBuffers:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Hb[d];e&&(L.deleteBuffer(e),e.name=0,Hb[d]=null)}},emscripten_glDeleteFramebuffers:function(a,b){for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=Ib[d];e&&(L.deleteFramebuffer(e),e.name=0,Ib[d]=null)}},emscripten_glDeleteProgram:function(a){if(a){var b=O[a];b?(L.deleteProgram(b),b.name=0,O[a]=null):R(1281)}},emscripten_glDeleteQueriesEXT:function(a,
b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Q[d];e&&(L.s.deleteQueryEXT(e),Q[d]=null)}},emscripten_glDeleteRenderbuffers:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Jb[d];e&&(L.deleteRenderbuffer(e),e.name=0,Jb[d]=null)}},emscripten_glDeleteShader:function(a){if(a){var b=P[a];b?(L.deleteShader(b),P[a]=null):R(1281)}},emscripten_glDeleteTextures:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Kb[d];e&&(L.deleteTexture(e),e.name=0,Kb[d]=null)}},emscripten_glDeleteVertexArraysOES:function(a,
b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];L.deleteVertexArray(Lb[d]);Lb[d]=null}},emscripten_glDepthFunc:function(a){L.depthFunc(a)},emscripten_glDepthMask:function(a){L.depthMask(!!a)},emscripten_glDepthRangef:function(a,b){L.depthRange(a,b)},emscripten_glDetachShader:function(a,b){L.detachShader(O[a],P[b])},emscripten_glDisable:function(a){L.disable(a)},emscripten_glDisableVertexAttribArray:function(a){L.disableVertexAttribArray(a)},emscripten_glDrawArrays:function(a,b,c){L.drawArrays(a,b,c)},emscripten_glDrawArraysInstancedANGLE:function(a,
b,c,d){L.drawArraysInstanced(a,b,c,d)},emscripten_glDrawBuffersWEBGL:function(a,b){for(var c=Jc[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];L.drawBuffers(c)},emscripten_glDrawElements:function(a,b,c,d){L.drawElements(a,b,c,d)},emscripten_glDrawElementsInstancedANGLE:function(a,b,c,d,e){L.drawElementsInstanced(a,b,c,d,e)},emscripten_glEnable:function(a){L.enable(a)},emscripten_glEnableVertexAttribArray:function(a){L.enableVertexAttribArray(a)},emscripten_glEndQueryEXT:function(a){L.s.endQueryEXT(a)},emscripten_glFinish:function(){L.finish()},
emscripten_glFlush:function(){L.flush()},emscripten_glFramebufferRenderbuffer:function(a,b,c,d){L.framebufferRenderbuffer(a,b,c,Jb[d])},emscripten_glFramebufferTexture2D:function(a,b,c,d,e){L.framebufferTexture2D(a,b,c,Kb[d],e)},emscripten_glFrontFace:function(a){L.frontFace(a)},emscripten_glGenBuffers:function(a,b){Kc(a,b,"createBuffer",Hb)},emscripten_glGenFramebuffers:function(a,b){Kc(a,b,"createFramebuffer",Ib)},emscripten_glGenQueriesEXT:function(a,b){for(var c=0;c<a;c++){var d=L.s.createQueryEXT();
if(!d){for(R(1282);c<a;)x[b+4*c++>>2]=0;break}var e=Pb(Q);d.name=e;Q[e]=d;x[b+4*c>>2]=e}},emscripten_glGenRenderbuffers:function(a,b){Kc(a,b,"createRenderbuffer",Jb)},emscripten_glGenTextures:function(a,b){Kc(a,b,"createTexture",Kb)},emscripten_glGenVertexArraysOES:function(a,b){Kc(a,b,"createVertexArray",Lb)},emscripten_glGenerateMipmap:function(a){L.generateMipmap(a)},emscripten_glGetActiveAttrib:function(a,b,c,d,e,f,g){Lc("getActiveAttrib",a,b,c,d,e,f,g)},emscripten_glGetActiveUniform:function(a,
b,c,d,e,f,g){Lc("getActiveUniform",a,b,c,d,e,f,g)},emscripten_glGetAttachedShaders:function(a,b,c,d){a=L.getAttachedShaders(O[a]);var e=a.length;e>b&&(e=b);x[c>>2]=e;for(b=0;b<e;++b)x[d+4*b>>2]=P.indexOf(a[b])},emscripten_glGetAttribLocation:function(a,b){return L.getAttribLocation(O[a],b?H(u,b):"")},emscripten_glGetBooleanv:function(a,b){Nc(a,b,4)},emscripten_glGetBufferParameteriv:function(a,b,c){c?x[c>>2]=L.getBufferParameter(a,b):R(1281)},emscripten_glGetError:function(){var a=L.getError()||Ob;
Ob=0;return a},emscripten_glGetFloatv:function(a,b){Nc(a,b,2)},emscripten_glGetFramebufferAttachmentParameteriv:function(a,b,c,d){a=L.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;x[d>>2]=a},emscripten_glGetIntegerv:function(a,b){Nc(a,b,0)},emscripten_glGetProgramInfoLog:function(a,b,c,d){a=L.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?G(a,d,b):0;c&&(x[c>>2]=b)},emscripten_glGetProgramiv:function(a,b,c){if(c)if(a>=
Gb)R(1281);else if(a=O[a],35716==b)a=L.getProgramInfoLog(a),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b){if(!a.J)for(b=0;b<L.getProgramParameter(a,35718);++b)a.J=Math.max(a.J,L.getActiveUniform(a,b).name.length+1);x[c>>2]=a.J}else if(35722==b){if(!a.H)for(b=0;b<L.getProgramParameter(a,35721);++b)a.H=Math.max(a.H,L.getActiveAttrib(a,b).name.length+1);x[c>>2]=a.H}else if(35381==b){if(!a.I)for(b=0;b<L.getProgramParameter(a,35382);++b)a.I=Math.max(a.I,L.getActiveUniformBlockName(a,
b).length+1);x[c>>2]=a.I}else x[c>>2]=L.getProgramParameter(a,b);else R(1281)},emscripten_glGetQueryObjecti64vEXT:Oc,emscripten_glGetQueryObjectivEXT:Pc,emscripten_glGetQueryObjectui64vEXT:Oc,emscripten_glGetQueryObjectuivEXT:Pc,emscripten_glGetQueryivEXT:function(a,b,c){c?x[c>>2]=L.s.getQueryEXT(a,b):R(1281)},emscripten_glGetRenderbufferParameteriv:function(a,b,c){c?x[c>>2]=L.getRenderbufferParameter(a,b):R(1281)},emscripten_glGetShaderInfoLog:function(a,b,c,d){a=L.getShaderInfoLog(P[a]);null===
a&&(a="(unknown error)");b=0<b&&d?G(a,d,b):0;c&&(x[c>>2]=b)},emscripten_glGetShaderPrecisionFormat:function(a,b,c,d){a=L.getShaderPrecisionFormat(a,b);x[c>>2]=a.rangeMin;x[c+4>>2]=a.rangeMax;x[d>>2]=a.precision},emscripten_glGetShaderSource:function(a,b,c,d){if(a=L.getShaderSource(P[a]))b=0<b&&d?G(a,d,b):0,c&&(x[c>>2]=b)},emscripten_glGetShaderiv:function(a,b,c){c?35716==b?(a=L.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),x[c>>2]=a?a.length+1:0):35720==b?(a=L.getShaderSource(P[a]),x[c>>
2]=a?a.length+1:0):x[c>>2]=L.getShaderParameter(P[a],b):R(1281)},emscripten_glGetString:function(a){var b=Mb[a];if(!b){switch(a){case 7939:b=L.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=S(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=L.getParameter(a))||R(1280);b=b&&S(b);break;case 7938:b=S("OpenGL ES 2.0 ("+L.getParameter(7938)+")");break;case 35724:b=L.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&
(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=S(b);break;default:R(1280)}Mb[a]=b}return b},emscripten_glGetTexParameterfv:function(a,b,c){c?z[c>>2]=L.getTexParameter(a,b):R(1281)},emscripten_glGetTexParameteriv:function(a,b,c){c?x[c>>2]=L.getTexParameter(a,b):R(1281)},emscripten_glGetUniformLocation:function(a,b){b=b?H(u,b):"";if(a=O[a]){Rc(a);var c=a.D,d=0,e=b,f=Qc(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.$[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||L.getUniformLocation(a,
b)))return d}else R(1281);return-1},emscripten_glGetUniformfv:function(a,b,c){Sc(a,b,c,2)},emscripten_glGetUniformiv:function(a,b,c){Sc(a,b,c,0)},emscripten_glGetVertexAttribPointerv:function(a,b,c){c?x[c>>2]=L.getVertexAttribOffset(a,b):R(1281)},emscripten_glGetVertexAttribfv:function(a,b,c){Tc(a,b,c,2)},emscripten_glGetVertexAttribiv:function(a,b,c){Tc(a,b,c,5)},emscripten_glHint:function(a,b){L.hint(a,b)},emscripten_glIsBuffer:function(a){return(a=Hb[a])?L.isBuffer(a):0},emscripten_glIsEnabled:function(a){return L.isEnabled(a)},
emscripten_glIsFramebuffer:function(a){return(a=Ib[a])?L.isFramebuffer(a):0},emscripten_glIsProgram:function(a){return(a=O[a])?L.isProgram(a):0},emscripten_glIsQueryEXT:function(a){return(a=Q[a])?L.s.isQueryEXT(a):0},emscripten_glIsRenderbuffer:function(a){return(a=Jb[a])?L.isRenderbuffer(a):0},emscripten_glIsShader:function(a){return(a=P[a])?L.isShader(a):0},emscripten_glIsTexture:function(a){return(a=Kb[a])?L.isTexture(a):0},emscripten_glIsVertexArrayOES:function(a){return(a=Lb[a])?L.isVertexArray(a):
0},emscripten_glLineWidth:function(a){L.lineWidth(a)},emscripten_glLinkProgram:function(a){a=O[a];L.linkProgram(a);a.D=0;a.$={}},emscripten_glPixelStorei:function(a,b){3317==a&&(Nb=b);L.pixelStorei(a,b)},emscripten_glPolygonOffset:function(a,b){L.polygonOffset(a,b)},emscripten_glQueryCounterEXT:function(a,b){L.s.queryCounterEXT(Q[a],b)},emscripten_glReadPixels:function(a,b,c,d,e,f,g){(g=Uc(f,e,c,d,g))?L.readPixels(a,b,c,d,e,f,g):R(1280)},emscripten_glReleaseShaderCompiler:function(){},emscripten_glRenderbufferStorage:function(a,
b,c,d){L.renderbufferStorage(a,b,c,d)},emscripten_glSampleCoverage:function(a,b){L.sampleCoverage(a,!!b)},emscripten_glScissor:function(a,b,c,d){L.scissor(a,b,c,d)},emscripten_glShaderBinary:function(){R(1280)},emscripten_glShaderSource:function(a,b,c,d){for(var e="",f=0;f<b;++f){var g=d?x[d+4*f>>2]:-1,m=x[c+4*f>>2];g=m?H(u,m,0>g?void 0:g):"";e+=g}L.shaderSource(P[a],e)},emscripten_glStencilFunc:function(a,b,c){L.stencilFunc(a,b,c)},emscripten_glStencilFuncSeparate:function(a,b,c,d){L.stencilFuncSeparate(a,
b,c,d)},emscripten_glStencilMask:function(a){L.stencilMask(a)},emscripten_glStencilMaskSeparate:function(a,b){L.stencilMaskSeparate(a,b)},emscripten_glStencilOp:function(a,b,c){L.stencilOp(a,b,c)},emscripten_glStencilOpSeparate:function(a,b,c,d){L.stencilOpSeparate(a,b,c,d)},emscripten_glTexImage2D:function(a,b,c,d,e,f,g,m,n){L.texImage2D(a,b,c,d,e,f,g,m,n?Uc(m,g,d,e,n):null)},emscripten_glTexParameterf:function(a,b,c){L.texParameterf(a,b,c)},emscripten_glTexParameterfv:function(a,b,c){L.texParameterf(a,
b,z[c>>2])},emscripten_glTexParameteri:function(a,b,c){L.texParameteri(a,b,c)},emscripten_glTexParameteriv:function(a,b,c){L.texParameteri(a,b,x[c>>2])},emscripten_glTexSubImage2D:function(a,b,c,d,e,f,g,m,n){var r=null;n&&(r=Uc(m,g,e,f,n));L.texSubImage2D(a,b,c,d,e,f,g,m,r)},emscripten_glUniform1f:function(a,b){L.uniform1f(X(a),b)},emscripten_glUniform1fv:function(a,b,c){if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);L.uniform1fv(X(a),d)},emscripten_glUniform1i:function(a,
b){L.uniform1i(X(a),b)},emscripten_glUniform1iv:function(a,b,c){if(288>=b)for(var d=Vc[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);L.uniform1iv(X(a),d)},emscripten_glUniform2f:function(a,b,c){L.uniform2f(X(a),b,c)},emscripten_glUniform2fv:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);L.uniform2fv(X(a),d)},emscripten_glUniform2i:function(a,b,c){L.uniform2i(X(a),b,c)},emscripten_glUniform2iv:function(a,
b,c){if(144>=b)for(var d=Vc[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);L.uniform2iv(X(a),d)},emscripten_glUniform3f:function(a,b,c,d){L.uniform3f(X(a),b,c,d)},emscripten_glUniform3fv:function(a,b,c){if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);L.uniform3fv(X(a),d)},emscripten_glUniform3i:function(a,b,c,d){L.uniform3i(X(a),b,c,d)},emscripten_glUniform3iv:function(a,
b,c){if(96>=b)for(var d=Vc[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);L.uniform3iv(X(a),d)},emscripten_glUniform4f:function(a,b,c,d,e){L.uniform4f(X(a),b,c,d,e)},emscripten_glUniform4fv:function(a,b,c){if(72>=b){var d=Y[4*b-1],e=z;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=z.subarray(c>>2,c+16*b>>2);L.uniform4fv(X(a),d)},emscripten_glUniform4i:function(a,b,c,d,e){L.uniform4i(X(a),
b,c,d,e)},emscripten_glUniform4iv:function(a,b,c){if(72>=b)for(var d=Vc[4*b-1],e=0;e<4*b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=x[c+(4*e+12)>>2];else d=x.subarray(c>>2,c+16*b>>2);L.uniform4iv(X(a),d)},emscripten_glUniformMatrix2fv:function(a,b,c,d){if(72>=b)for(var e=Y[4*b-1],f=0;f<4*b;f+=4)e[f]=z[d+4*f>>2],e[f+1]=z[d+(4*f+4)>>2],e[f+2]=z[d+(4*f+8)>>2],e[f+3]=z[d+(4*f+12)>>2];else e=z.subarray(d>>2,d+16*b>>2);L.uniformMatrix2fv(X(a),!!c,e)},emscripten_glUniformMatrix3fv:function(a,
b,c,d){if(32>=b)for(var e=Y[9*b-1],f=0;f<9*b;f+=9)e[f]=z[d+4*f>>2],e[f+1]=z[d+(4*f+4)>>2],e[f+2]=z[d+(4*f+8)>>2],e[f+3]=z[d+(4*f+12)>>2],e[f+4]=z[d+(4*f+16)>>2],e[f+5]=z[d+(4*f+20)>>2],e[f+6]=z[d+(4*f+24)>>2],e[f+7]=z[d+(4*f+28)>>2],e[f+8]=z[d+(4*f+32)>>2];else e=z.subarray(d>>2,d+36*b>>2);L.uniformMatrix3fv(X(a),!!c,e)},emscripten_glUniformMatrix4fv:function(a,b,c,d){if(18>=b){var e=Y[16*b-1],f=z;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=
f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=z.subarray(d>>2,d+64*b>>2);L.uniformMatrix4fv(X(a),!!c,e)},emscripten_glUseProgram:function(a){a=O[a];L.useProgram(a);L.ba=a},emscripten_glValidateProgram:function(a){L.validateProgram(O[a])},emscripten_glVertexAttrib1f:function(a,b){L.vertexAttrib1f(a,b)},emscripten_glVertexAttrib1fv:function(a,b){L.vertexAttrib1f(a,z[b>>
2])},emscripten_glVertexAttrib2f:function(a,b,c){L.vertexAttrib2f(a,b,c)},emscripten_glVertexAttrib2fv:function(a,b){L.vertexAttrib2f(a,z[b>>2],z[b+4>>2])},emscripten_glVertexAttrib3f:function(a,b,c,d){L.vertexAttrib3f(a,b,c,d)},emscripten_glVertexAttrib3fv:function(a,b){L.vertexAttrib3f(a,z[b>>2],z[b+4>>2],z[b+8>>2])},emscripten_glVertexAttrib4f:function(a,b,c,d,e){L.vertexAttrib4f(a,b,c,d,e)},emscripten_glVertexAttrib4fv:function(a,b){L.vertexAttrib4f(a,z[b>>2],z[b+4>>2],z[b+8>>2],z[b+12>>2])},
emscripten_glVertexAttribDivisorANGLE:function(a,b){L.vertexAttribDivisor(a,b)},emscripten_glVertexAttribPointer:function(a,b,c,d,e,f){L.vertexAttribPointer(a,b,c,!!d,e,f)},emscripten_glViewport:function(a,b,c,d){L.viewport(a,b,c,d)},emscripten_has_asyncify:()=>0,emscripten_request_fullscreen_strategy:function(a,b,c){return Wc(a,{O:x[c>>2],M:x[c+4>>2],ia:x[c+8>>2],fa:b,F:x[c+12>>2],T:x[c+16>>2]})},emscripten_request_pointerlock:function(a,b){a=W(a);return a?a.requestPointerLock?dc()?Hc(a):b?(bc(Hc,
2,[a]),1):-2:-1:-4},emscripten_sample_gamepad_data:function(){return(kc=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},emscripten_set_beforeunload_callback_on_thread:function(a,b,c){return"undefined"==typeof onbeforeunload?-1:1!==c?-5:Xc(a,b)},emscripten_set_blur_callback_on_thread:function(a,b,c,d){return Yc(a,b,c,d,12,"blur")},emscripten_set_canvas_element_size:Bc,emscripten_set_element_css_size:function(a,b,c){a=W(a);if(!a)return-4;
a.style.width=b+"px";a.style.height=c+"px";return 0},emscripten_set_focus_callback_on_thread:function(a,b,c,d){return Yc(a,b,c,d,13,"focus")},emscripten_set_fullscreenchange_callback_on_thread:function(a,b,c,d){if(!ic())return-1;a=W(a);if(!a)return-4;Zc(a,b,c,d,"webkitfullscreenchange");return Zc(a,b,c,d,"fullscreenchange")},emscripten_set_gamepadconnected_callback_on_thread:function(a,b,c){return navigator.getGamepads||navigator.webkitGetGamepads?$c(a,b,c,26,"gamepadconnected"):-1},emscripten_set_gamepaddisconnected_callback_on_thread:function(a,
b,c){return navigator.getGamepads||navigator.webkitGetGamepads?$c(a,b,c,27,"gamepaddisconnected"):-1},emscripten_set_keydown_callback_on_thread:function(a,b,c,d){return ad(a,b,c,d,2,"keydown")},emscripten_set_keypress_callback_on_thread:function(a,b,c,d){return ad(a,b,c,d,1,"keypress")},emscripten_set_keyup_callback_on_thread:function(a,b,c,d){return ad(a,b,c,d,3,"keyup")},emscripten_set_main_loop:function(a,b,c){a=B.get(a);Za(a,b,c)},emscripten_set_mousedown_callback_on_thread:function(a,b,c,d){return cd(a,
b,c,d,5,"mousedown")},emscripten_set_mouseenter_callback_on_thread:function(a,b,c,d){return cd(a,b,c,d,33,"mouseenter")},emscripten_set_mouseleave_callback_on_thread:function(a,b,c,d){return cd(a,b,c,d,34,"mouseleave")},emscripten_set_mousemove_callback_on_thread:function(a,b,c,d){return cd(a,b,c,d,8,"mousemove")},emscripten_set_mouseup_callback_on_thread:function(a,b,c,d){return cd(a,b,c,d,6,"mouseup")},emscripten_set_pointerlockchange_callback_on_thread:function(a,b,c,d){if(!document||!document.body||
!(document.body.requestPointerLock||document.body.G||document.body.oa||document.body.la))return-1;a=W(a);if(!a)return-4;dd(a,b,c,d,"mozpointerlockchange");dd(a,b,c,d,"webkitpointerlockchange");dd(a,b,c,d,"mspointerlockchange");return dd(a,b,c,d,"pointerlockchange")},emscripten_set_resize_callback_on_thread:function(a,b,c,d){return ed(a,b,c,d)},emscripten_set_touchcancel_callback_on_thread:function(a,b,c,d){return fd(a,b,c,d,25,"touchcancel")},emscripten_set_touchend_callback_on_thread:function(a,
b,c,d){return fd(a,b,c,d,23,"touchend")},emscripten_set_touchmove_callback_on_thread:function(a,b,c,d){return fd(a,b,c,d,24,"touchmove")},emscripten_set_touchstart_callback_on_thread:function(a,b,c,d){return fd(a,b,c,d,22,"touchstart")},emscripten_set_visibilitychange_callback_on_thread:function(a,b,c){return gd(a,b,c)},emscripten_set_wheel_callback_on_thread:function(a,b,c,d){return(a=W(a))?"undefined"!=typeof a.onwheel?hd(a,b,c,d):-1:-4},emscripten_set_window_title:function(a){ea(a?H(u,a):"")},
emscripten_sleep:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},environ_get:(a,b)=>{var c=0;ld().forEach(function(d,e){var f=b+c;y[a+4*e>>2]=f;Ia(d,f);c+=d.length+1});return 0},environ_sizes_get:(a,b)=>{var c=ld();y[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});y[b>>2]=d;return 0},fd_close:()=>52,fd_read:()=>52,fd_seek:function(){return 70},fd_write:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=y[b>>2],m=
y[b+4>>2];b+=8;for(var n=0;n<m;n++)nd(a,u[g+n]);e+=m}y[d>>2]=e;return 0},invoke_iii:yd,invoke_iiii:zd,invoke_iiiii:Ad,invoke_vi:Bd,proc_exit:Va};
(function(){function a(c){p=c=c.exports;ja=p.memory;var d=ja.buffer;h.HEAP8=t=new Int8Array(d);h.HEAP16=la=new Int16Array(d);h.HEAP32=x=new Int32Array(d);h.HEAPU8=u=new Uint8Array(d);h.HEAPU16=ma=new Uint16Array(d);h.HEAPU32=y=new Uint32Array(d);h.HEAPF32=z=new Float32Array(d);h.HEAPF64=A=new Float64Array(d);h.HEAP64=na=new BigInt64Array(d);h.HEAPU64=new BigUint64Array(d);B=p.__indirect_function_table;D--;h.monitorRunDependencies&&h.monitorRunDependencies(D);0==D&&(null!==va&&(clearInterval(va),va=
null),wa&&(d=wa,wa=null,d()));return c}var b={env:Cd,wasi_snapshot_preview1:Cd};D++;h.monitorRunDependencies&&h.monitorRunDependencies(D);if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return l("Module.instantiateWasm callback failed with error: "+c),!1}Ca(b,function(c){a(c.instance)});return{}})();var F=a=>(F=p.malloc)(a),Dd=h.__start=()=>(Dd=h.__start=p._start)(),Ed=(a,b)=>(Ed=p.setThrew)(a,b),Wb=()=>(Wb=p.stackSave)(),Xb=a=>(Xb=p.stackRestore)(a),yc=a=>(yc=p.stackAlloc)(a);
function yd(a,b,c){var d=Wb();try{return B.get(a)(b,c)}catch(e){Xb(d);if(e!==e+0)throw e;Ed(1,0)}}function Ad(a,b,c,d,e){var f=Wb();try{return B.get(a)(b,c,d,e)}catch(g){Xb(f);if(g!==g+0)throw g;Ed(1,0)}}function zd(a,b,c,d){var e=Wb();try{return B.get(a)(b,c,d)}catch(f){Xb(e);if(f!==f+0)throw f;Ed(1,0)}}function Bd(a,b){var c=Wb();try{B.get(a)(b)}catch(d){Xb(c);if(d!==d+0)throw d;Ed(1,0)}}var Fd,xd=void 0;wa=function Gd(){Fd||Hd();Fd||(wa=Gd)};
function Id(a=[]){var b=Dd;xd=[ca].concat(a);try{b(),ka=0,noExitRuntime||0<C||(I(ra),Xa(),ta=!0),Va(0)}catch(c){Wa(c)}}
function Hd(){var a=ba;function b(){if(!Fd&&(Fd=!0,h.calledRun=!0,!q)){I(pa);I(qa);if(h.onRuntimeInitialized)h.onRuntimeInitialized();Jd&&Id(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();sa.unshift(c)}I(sa)}}if(!(0<D)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)ua();I(oa);0<D||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):
b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Jd=!0;h.noInitialRun&&(Jd=!1);Hd();
